#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_Prj_Zapper2

#include "Basic.hpp"

#include "B_Prj_Zapper2_classes.hpp"
#include "B_Prj_Zapper2_parameters.hpp"


#pragma pack(push, 0x4)
namespace SDK
{

// Function B_Prj_Zapper2.B_Prj_Zapper2_C.ExecuteUbergraph_B_Prj_Zapper2
// (HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AB_Prj_Zapper2_C::ExecuteUbergraph_B_Prj_Zapper2(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Prj_Zapper2_C", "ExecuteUbergraph_B_Prj_Zapper2");

	Params::B_Prj_Zapper2_C_ExecuteUbergraph_B_Prj_Zapper2 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Prj_Zapper2.B_Prj_Zapper2_C.OnStop
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FHitResult&                Hit                                                    (ConstParm, Parm, OutParm, ReferenceParm, ContainsInstancedReference)

void AB_Prj_Zapper2_C::OnStop(const struct FHitResult& Hit)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Prj_Zapper2_C", "OnStop");

	Params::B_Prj_Zapper2_C_OnStop Parms{};

	Parms.Hit = std::move(Hit);

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Prj_Zapper2.B_Prj_Zapper2_C.ReceiveBeginPlay
// (Event, Public, BlueprintEvent)

void AB_Prj_Zapper2_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Prj_Zapper2_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Prj_Zapper2.B_Prj_Zapper2_C.ReceiveAnyDamage
// (BlueprintAuthorityOnly, Event, Public, BlueprintEvent)
// Parameters:
// float                                   Damage                                                 (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// const class UDamageType*                DamageType                                             (ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class AController*                      InstigatedBy                                           (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class AActor*                           DamageCauser                                           (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AB_Prj_Zapper2_C::ReceiveAnyDamage(float Damage, const class UDamageType* DamageType, class AController* InstigatedBy, class AActor* DamageCauser)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Prj_Zapper2_C", "ReceiveAnyDamage");

	Params::B_Prj_Zapper2_C_ReceiveAnyDamage Parms{};

	Parms.Damage = Damage;
	Parms.DamageType = DamageType;
	Parms.InstigatedBy = InstigatedBy;
	Parms.DamageCauser = DamageCauser;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Prj_Zapper2.B_Prj_Zapper2_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void AB_Prj_Zapper2_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Prj_Zapper2_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Prj_Zapper2.B_Prj_Zapper2_C.OnRep_Impact Location
// (BlueprintCallable, BlueprintEvent)

void AB_Prj_Zapper2_C::OnRep_Impact_Location()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Prj_Zapper2_C", "OnRep_Impact Location");

	UObject::ProcessEvent(Func, nullptr);
}

}

#pragma pack(pop)
