#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_RocketLauncher_Generic

#include "Basic.hpp"

#include "B_RocketLauncher_Generic_classes.hpp"
#include "B_RocketLauncher_Generic_parameters.hpp"


#pragma pack(push, 0x4)
namespace SDK
{

// Function B_RocketLauncher_Generic.B_RocketLauncher_Generic_C.ExecuteUbergraph_B_RocketLauncher_Generic
// ()
// Parameters:
// int32                                   EntryPoint                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AB_RocketLauncher_Generic_C::ExecuteUbergraph_B_RocketLauncher_Generic(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_RocketLauncher_Generic_C", "ExecuteUbergraph_B_RocketLauncher_Generic");

	Params::B_RocketLauncher_Generic_C_ExecuteUbergraph_B_RocketLauncher_Generic Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_RocketLauncher_Generic.B_RocketLauncher_Generic_C.Muzzle Flash FX
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Condition                                              (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AB_RocketLauncher_Generic_C::Muzzle_Flash_FX(bool Condition)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_RocketLauncher_Generic_C", "Muzzle Flash FX");

	Params::B_RocketLauncher_Generic_C_Muzzle_Flash_FX Parms{};

	Parms.Condition = Condition;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_RocketLauncher_Generic.B_RocketLauncher_Generic_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void AB_RocketLauncher_Generic_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_RocketLauncher_Generic_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_RocketLauncher_Generic.B_RocketLauncher_Generic_C.IsUsingScope
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool*                                   UsingScope                                             (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AB_RocketLauncher_Generic_C::IsUsingScope(bool* UsingScope)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_RocketLauncher_Generic_C", "IsUsingScope");

	Params::B_RocketLauncher_Generic_C_IsUsingScope Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (UsingScope != nullptr)
		*UsingScope = Parms.UsingScope;
}

}

#pragma pack(pop)
