#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_Shotgun_Standard

#include "Basic.hpp"

#include "B_Shotgun_Generic_classes.hpp"


#pragma pack(push, 0x4)
namespace SDK
{

// BlueprintGeneratedClass B_Shotgun_Standard.B_Shotgun_Standard_C
// 0x0000 (0x0774 - 0x0774)
class AB_Shotgun_Standard_C final : public AB_Shotgun_Generic_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"B_Shotgun_Standard_C">();
	}
	static class AB_Shotgun_Standard_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AB_Shotgun_Standard_C>();
	}
};
static_assert(alignof(AB_Shotgun_Standard_C) == 0x000004, "Wrong alignment on AB_Shotgun_Standard_C");
static_assert(sizeof(AB_Shotgun_Standard_C) == 0x000774, "Wrong size on AB_Shotgun_Standard_C");

}

#pragma pack(pop)
