#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_Shotgun_Break

#include "Basic.hpp"

#include "B_Shotgun_Break_classes.hpp"
#include "B_Shotgun_Break_parameters.hpp"


#pragma pack(push, 0x4)
namespace SDK
{

// Function B_Shotgun_Break.B_Shotgun_Break_C.ExecuteUbergraph_B_Shotgun_Break
// (HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AB_Shotgun_Break_C::ExecuteUbergraph_B_Shotgun_Break(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Shotgun_Break_C", "ExecuteUbergraph_B_Shotgun_Break");

	Params::B_Shotgun_Break_C_ExecuteUbergraph_B_Shotgun_Break Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Shotgun_Break.B_Shotgun_Break_C.OnPlayWeaponFireFX
// (BlueprintCosmetic, Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bPersistentFire                                        (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AB_Shotgun_Break_C::OnPlayWeaponFireFX(bool bPersistentFire)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Shotgun_Break_C", "OnPlayWeaponFireFX");

	Params::B_Shotgun_Break_C_OnPlayWeaponFireFX Parms{};

	Parms.bPersistentFire = bPersistentFire;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Shotgun_Break.B_Shotgun_Break_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void AB_Shotgun_Break_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Shotgun_Break_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

#pragma pack(pop)
