#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_UtilityItem_Generic

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


#pragma pack(push, 0x4)
namespace SDK
{

// BlueprintGeneratedClass B_UtilityItem_Generic.B_UtilityItem_Generic_C
// 0x0000 (0x05F4 - 0x05F4)
class AB_UtilityItem_Generic_C final : public AFortWeapon
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"B_UtilityItem_Generic_C">();
	}
	static class AB_UtilityItem_Generic_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AB_UtilityItem_Generic_C>();
	}
};
static_assert(alignof(AB_UtilityItem_Generic_C) == 0x000004, "Wrong alignment on AB_UtilityItem_Generic_C");
static_assert(sizeof(AB_UtilityItem_Generic_C) == 0x0005F4, "Wrong size on AB_UtilityItem_Generic_C");

}

#pragma pack(pop)
