#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BluGloManager

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "AIModule_structs.hpp"
#include "FortniteGame_structs.hpp"
#include "GameplayTags_structs.hpp"


#pragma pack(push, 0x4)
namespace SDK::Params
{

// Function BluGloManager.BluGloManager_C.ExecuteUbergraph_BluGloManager
// 0x03E0 (0x03E0 - 0x0000)
struct BluGloManager_C_ExecuteUbergraph_BluGloManager final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_True_if_break_was_hit_Variable;          // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0009(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_A[0x2];                                        // 0x000A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Variable;                                 // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable;                                // 0x0014(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Not_PreBool_ReturnValue2;                 // 0x0015(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_16[0x2];                                       // 0x0016(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Variable2;                                // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	int32                                         CallFunc_Add_IntInt_ReturnValue2;                  // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FFortMissionEvent                      K2Node_Event_MissionEvent;                         // 0x0020(0x006C)(ConstParm)
	struct FGuid                                  K2Node_HandleMissionEvent_MissionGuid2;            // 0x008C(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FGameplayTagContainer                  K2Node_HandleMissionEvent_ObjectiveHandle2;        // 0x009C(0x0018)()
	class UFortMissionEventParams*                K2Node_HandleMissionEvent_Params2;                 // 0x00B4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_HandleMissionEvent_DO_NOT_USE_THIS_OR_VARIABLES_BELOW2; // 0x00B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_B9[0x3];                                       // 0x00B9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                K2Node_HandleMissionEvent_EventFocus2;             // 0x00BC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	const class UDataAsset*                       K2Node_HandleMissionEvent_EventContent2;           // 0x00C0(0x0004)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor)
	class AActor*                                 K2Node_HandleMissionEvent_EventInstigator2;        // 0x00C4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	int32                                         K2Node_HandleMissionEvent_GenericInt2;             // 0x00C8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	float                                         K2Node_HandleMissionEvent_GenericFloat2;           // 0x00CC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	class FText                                   K2Node_HandleMissionEvent_GenericText2;            // 0x00D0(0x000C)(ConstParm)
	struct FGameplayTagContainer                  K2Node_HandleMissionEvent_GameplayTags2;           // 0x00DC(0x0018)()
	struct FFortMissionEvent                      K2Node_HandleMissionEvent_MissionEvent2;           // 0x00F4(0x006C)(ConstParm)
	class UEnvQueryInstanceBlueprintWrapper*      K2Node_CustomEvent_QueryInstance;                  // 0x0160(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	EEnvQueryStatus                               K2Node_CustomEvent_QueryStatus;                    // 0x0164(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_165[0x3];                                      // 0x0165(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGuid                                  K2Node_HandleMissionEvent_MissionGuid;             // 0x0168(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FGameplayTagContainer                  K2Node_HandleMissionEvent_ObjectiveHandle;         // 0x0178(0x0018)()
	class UFortMissionEventParams*                K2Node_HandleMissionEvent_Params;                  // 0x0190(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_HandleMissionEvent_DO_NOT_USE_THIS_OR_VARIABLES_BELOW; // 0x0194(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_195[0x3];                                      // 0x0195(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                K2Node_HandleMissionEvent_EventFocus;              // 0x0198(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	const class UDataAsset*                       K2Node_HandleMissionEvent_EventContent;            // 0x019C(0x0004)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor)
	class AActor*                                 K2Node_HandleMissionEvent_EventInstigator;         // 0x01A0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	int32                                         K2Node_HandleMissionEvent_GenericInt;              // 0x01A4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	float                                         K2Node_HandleMissionEvent_GenericFloat;            // 0x01A8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	class FText                                   K2Node_HandleMissionEvent_GenericText;             // 0x01AC(0x000C)(ConstParm)
	struct FGameplayTagContainer                  K2Node_HandleMissionEvent_GameplayTags;            // 0x01B8(0x0018)()
	struct FFortMissionEvent                      K2Node_HandleMissionEvent_MissionEvent;            // 0x01D0(0x006C)(ConstParm)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x023C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_23D[0x3];                                      // 0x023D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FVector>                        CallFunc_GetResultsAsLocations_ReturnValue;        // 0x0240(0x000C)(ZeroConstructor, ReferenceParm)
	TArray<class ATiered_BluGlo_Parent_C*>        CallFunc_GetAllActorsOfClass_OutActors;            // 0x024C(0x000C)(ZeroConstructor, ReferenceParm)
	struct FVector                                CallFunc_Array_Get_Item;                           // 0x0258(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0264(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_268[0x8];                                      // 0x0268(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_Conv_VectorToTransform_ReturnValue;       // 0x0270(0x0030)(IsPlainOldData, NoDestructor)
	int32                                         CallFunc_Array_Length_ReturnValue2;                // 0x02A0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	class AActor*                                 CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue; // 0x02A4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_GreaterEqual_IntInt_ReturnValue;          // 0x02A8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2A9[0x3];                                      // 0x02A9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class ABluGlo_Node_C*                         CallFunc_FinishSpawningActor_ReturnValue;          // 0x02AC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x02B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2B1[0x3];                                      // 0x02B1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue3;                // 0x02B4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	class ATiered_BluGlo_Parent_C*                CallFunc_Array_Get_Item2;                          // 0x02B8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	int32                                         CallFunc_Array_Add_ReturnValue;                    // 0x02BC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_GreaterEqual_IntInt_ReturnValue2;         // 0x02C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2C1[0x3];                                      // 0x02C1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x02C4(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FTransform                             CallFunc_Conv_VectorToTransform_ReturnValue2;      // 0x02D0(0x0030)(IsPlainOldData, NoDestructor)
	class AActor*                                 CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue2; // 0x0300(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	class UEnvQueryInstanceBlueprintWrapper*      CallFunc_RunEQSQuery_ReturnValue;                  // 0x0304(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	class ABluGlo_Node_C*                         CallFunc_FinishSpawningActor_ReturnValue2;         // 0x0308(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	int32                                         CallFunc_Subtract_IntInt_ReturnValue;              // 0x030C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue2;         // 0x0310(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_LessEqual_IntInt_ReturnValue;             // 0x031C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue2;                  // 0x031D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_31E[0x2];                                      // 0x031E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue3;         // 0x0320(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	class UParticleSystemComponent*               CallFunc_SpawnEmitterAtLocation_ReturnValue;       // 0x032C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	float                                         CallFunc_MakeLiteralFloat_ReturnValue;             // 0x0330(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_CustomEvent_On_off;                         // 0x0334(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_335[0x3];                                      // 0x0335(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0338(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x033C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_33D[0x3];                                      // 0x033D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue3;                  // 0x0340(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue3;                  // 0x0344(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_345[0x3];                                      // 0x0345(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Loop_Counter_Variable2;                   // 0x0348(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	int32                                         Temp_int_Array_Index_Variable2;                    // 0x034C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Less_IntInt_ReturnValue2;                 // 0x0350(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_351[0x3];                                      // 0x0351(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class ATiered_BluGlo_Parent_C*                CallFunc_Array_Get_Item3;                          // 0x0354(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	int32                                         CallFunc_Array_Add_ReturnValue2;                   // 0x0358(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	int32                                         CallFunc_Add_IntInt_ReturnValue4;                  // 0x035C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue4;         // 0x0360(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	int32                                         CallFunc_Subtract_IntInt_ReturnValue2;             // 0x036C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_GetRandomPointInNavigableRadius_ReturnValue; // 0x0370(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_LessEqual_IntInt_ReturnValue2;            // 0x037C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_37D[0x3];                                      // 0x037D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_Conv_VectorToTransform_ReturnValue3;      // 0x0380(0x0030)(IsPlainOldData, NoDestructor)
	class AActor*                                 CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue3; // 0x03B0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	class ABluGlo_Node_C*                         CallFunc_FinishSpawningActor_ReturnValue3;         // 0x03B4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	TDelegate<void(class UEnvQueryInstanceBlueprintWrapper* QueryInstance, EEnvQueryStatus QueryStatus)> K2Node_CreateDelegate_OutputDelegate;              // 0x03B8(0x0010)(ZeroConstructor, NoDestructor)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue5;         // 0x03C8(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	float                                         CallFunc_MakeLiteralFloat_ReturnValue2;            // 0x03D4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BluGloManager_C_ExecuteUbergraph_BluGloManager) == 0x000010, "Wrong alignment on BluGloManager_C_ExecuteUbergraph_BluGloManager");
static_assert(sizeof(BluGloManager_C_ExecuteUbergraph_BluGloManager) == 0x0003E0, "Wrong size on BluGloManager_C_ExecuteUbergraph_BluGloManager");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, EntryPoint) == 0x000000, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::EntryPoint' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, Temp_int_Array_Index_Variable) == 0x000004, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, Temp_bool_True_if_break_was_hit_Variable) == 0x000008, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::Temp_bool_True_if_break_was_hit_Variable' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, CallFunc_Not_PreBool_ReturnValue) == 0x000009, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, Temp_int_Variable) == 0x00000C, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::Temp_int_Variable' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, CallFunc_Add_IntInt_ReturnValue) == 0x000010, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, Temp_bool_Variable) == 0x000014, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, CallFunc_Not_PreBool_ReturnValue2) == 0x000015, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::CallFunc_Not_PreBool_ReturnValue2' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, Temp_int_Variable2) == 0x000018, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::Temp_int_Variable2' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, CallFunc_Add_IntInt_ReturnValue2) == 0x00001C, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::CallFunc_Add_IntInt_ReturnValue2' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, K2Node_Event_MissionEvent) == 0x000020, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::K2Node_Event_MissionEvent' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, K2Node_HandleMissionEvent_MissionGuid2) == 0x00008C, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::K2Node_HandleMissionEvent_MissionGuid2' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, K2Node_HandleMissionEvent_ObjectiveHandle2) == 0x00009C, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::K2Node_HandleMissionEvent_ObjectiveHandle2' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, K2Node_HandleMissionEvent_Params2) == 0x0000B4, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::K2Node_HandleMissionEvent_Params2' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, K2Node_HandleMissionEvent_DO_NOT_USE_THIS_OR_VARIABLES_BELOW2) == 0x0000B8, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::K2Node_HandleMissionEvent_DO_NOT_USE_THIS_OR_VARIABLES_BELOW2' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, K2Node_HandleMissionEvent_EventFocus2) == 0x0000BC, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::K2Node_HandleMissionEvent_EventFocus2' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, K2Node_HandleMissionEvent_EventContent2) == 0x0000C0, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::K2Node_HandleMissionEvent_EventContent2' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, K2Node_HandleMissionEvent_EventInstigator2) == 0x0000C4, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::K2Node_HandleMissionEvent_EventInstigator2' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, K2Node_HandleMissionEvent_GenericInt2) == 0x0000C8, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::K2Node_HandleMissionEvent_GenericInt2' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, K2Node_HandleMissionEvent_GenericFloat2) == 0x0000CC, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::K2Node_HandleMissionEvent_GenericFloat2' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, K2Node_HandleMissionEvent_GenericText2) == 0x0000D0, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::K2Node_HandleMissionEvent_GenericText2' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, K2Node_HandleMissionEvent_GameplayTags2) == 0x0000DC, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::K2Node_HandleMissionEvent_GameplayTags2' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, K2Node_HandleMissionEvent_MissionEvent2) == 0x0000F4, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::K2Node_HandleMissionEvent_MissionEvent2' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, K2Node_CustomEvent_QueryInstance) == 0x000160, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::K2Node_CustomEvent_QueryInstance' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, K2Node_CustomEvent_QueryStatus) == 0x000164, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::K2Node_CustomEvent_QueryStatus' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, K2Node_HandleMissionEvent_MissionGuid) == 0x000168, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::K2Node_HandleMissionEvent_MissionGuid' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, K2Node_HandleMissionEvent_ObjectiveHandle) == 0x000178, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::K2Node_HandleMissionEvent_ObjectiveHandle' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, K2Node_HandleMissionEvent_Params) == 0x000190, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::K2Node_HandleMissionEvent_Params' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, K2Node_HandleMissionEvent_DO_NOT_USE_THIS_OR_VARIABLES_BELOW) == 0x000194, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::K2Node_HandleMissionEvent_DO_NOT_USE_THIS_OR_VARIABLES_BELOW' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, K2Node_HandleMissionEvent_EventFocus) == 0x000198, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::K2Node_HandleMissionEvent_EventFocus' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, K2Node_HandleMissionEvent_EventContent) == 0x00019C, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::K2Node_HandleMissionEvent_EventContent' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, K2Node_HandleMissionEvent_EventInstigator) == 0x0001A0, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::K2Node_HandleMissionEvent_EventInstigator' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, K2Node_HandleMissionEvent_GenericInt) == 0x0001A4, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::K2Node_HandleMissionEvent_GenericInt' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, K2Node_HandleMissionEvent_GenericFloat) == 0x0001A8, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::K2Node_HandleMissionEvent_GenericFloat' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, K2Node_HandleMissionEvent_GenericText) == 0x0001AC, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::K2Node_HandleMissionEvent_GenericText' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, K2Node_HandleMissionEvent_GameplayTags) == 0x0001B8, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::K2Node_HandleMissionEvent_GameplayTags' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, K2Node_HandleMissionEvent_MissionEvent) == 0x0001D0, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::K2Node_HandleMissionEvent_MissionEvent' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x00023C, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, CallFunc_GetResultsAsLocations_ReturnValue) == 0x000240, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::CallFunc_GetResultsAsLocations_ReturnValue' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, CallFunc_GetAllActorsOfClass_OutActors) == 0x00024C, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::CallFunc_GetAllActorsOfClass_OutActors' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, CallFunc_Array_Get_Item) == 0x000258, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, CallFunc_Array_Length_ReturnValue) == 0x000264, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, CallFunc_Conv_VectorToTransform_ReturnValue) == 0x000270, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::CallFunc_Conv_VectorToTransform_ReturnValue' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, CallFunc_Array_Length_ReturnValue2) == 0x0002A0, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::CallFunc_Array_Length_ReturnValue2' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue) == 0x0002A4, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, CallFunc_GreaterEqual_IntInt_ReturnValue) == 0x0002A8, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::CallFunc_GreaterEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, CallFunc_FinishSpawningActor_ReturnValue) == 0x0002AC, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::CallFunc_FinishSpawningActor_ReturnValue' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, CallFunc_BooleanAND_ReturnValue) == 0x0002B0, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, CallFunc_Array_Length_ReturnValue3) == 0x0002B4, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::CallFunc_Array_Length_ReturnValue3' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, CallFunc_Array_Get_Item2) == 0x0002B8, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::CallFunc_Array_Get_Item2' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, CallFunc_Array_Add_ReturnValue) == 0x0002BC, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::CallFunc_Array_Add_ReturnValue' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, CallFunc_GreaterEqual_IntInt_ReturnValue2) == 0x0002C0, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::CallFunc_GreaterEqual_IntInt_ReturnValue2' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, CallFunc_K2_GetActorLocation_ReturnValue) == 0x0002C4, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, CallFunc_Conv_VectorToTransform_ReturnValue2) == 0x0002D0, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::CallFunc_Conv_VectorToTransform_ReturnValue2' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue2) == 0x000300, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue2' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, CallFunc_RunEQSQuery_ReturnValue) == 0x000304, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::CallFunc_RunEQSQuery_ReturnValue' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, CallFunc_FinishSpawningActor_ReturnValue2) == 0x000308, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::CallFunc_FinishSpawningActor_ReturnValue2' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, CallFunc_Subtract_IntInt_ReturnValue) == 0x00030C, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::CallFunc_Subtract_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, CallFunc_K2_GetActorLocation_ReturnValue2) == 0x000310, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::CallFunc_K2_GetActorLocation_ReturnValue2' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, CallFunc_LessEqual_IntInt_ReturnValue) == 0x00031C, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::CallFunc_LessEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, CallFunc_BooleanAND_ReturnValue2) == 0x00031D, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::CallFunc_BooleanAND_ReturnValue2' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, CallFunc_K2_GetActorLocation_ReturnValue3) == 0x000320, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::CallFunc_K2_GetActorLocation_ReturnValue3' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, CallFunc_SpawnEmitterAtLocation_ReturnValue) == 0x00032C, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::CallFunc_SpawnEmitterAtLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, CallFunc_MakeLiteralFloat_ReturnValue) == 0x000330, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::CallFunc_MakeLiteralFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, K2Node_CustomEvent_On_off) == 0x000334, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::K2Node_CustomEvent_On_off' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, Temp_int_Loop_Counter_Variable) == 0x000338, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, CallFunc_Less_IntInt_ReturnValue) == 0x00033C, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, CallFunc_Add_IntInt_ReturnValue3) == 0x000340, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::CallFunc_Add_IntInt_ReturnValue3' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, CallFunc_BooleanAND_ReturnValue3) == 0x000344, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::CallFunc_BooleanAND_ReturnValue3' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, Temp_int_Loop_Counter_Variable2) == 0x000348, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::Temp_int_Loop_Counter_Variable2' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, Temp_int_Array_Index_Variable2) == 0x00034C, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::Temp_int_Array_Index_Variable2' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, CallFunc_Less_IntInt_ReturnValue2) == 0x000350, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::CallFunc_Less_IntInt_ReturnValue2' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, CallFunc_Array_Get_Item3) == 0x000354, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::CallFunc_Array_Get_Item3' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, CallFunc_Array_Add_ReturnValue2) == 0x000358, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::CallFunc_Array_Add_ReturnValue2' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, CallFunc_Add_IntInt_ReturnValue4) == 0x00035C, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::CallFunc_Add_IntInt_ReturnValue4' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, CallFunc_K2_GetActorLocation_ReturnValue4) == 0x000360, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::CallFunc_K2_GetActorLocation_ReturnValue4' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, CallFunc_Subtract_IntInt_ReturnValue2) == 0x00036C, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::CallFunc_Subtract_IntInt_ReturnValue2' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, CallFunc_GetRandomPointInNavigableRadius_ReturnValue) == 0x000370, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::CallFunc_GetRandomPointInNavigableRadius_ReturnValue' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, CallFunc_LessEqual_IntInt_ReturnValue2) == 0x00037C, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::CallFunc_LessEqual_IntInt_ReturnValue2' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, CallFunc_Conv_VectorToTransform_ReturnValue3) == 0x000380, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::CallFunc_Conv_VectorToTransform_ReturnValue3' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue3) == 0x0003B0, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue3' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, CallFunc_FinishSpawningActor_ReturnValue3) == 0x0003B4, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::CallFunc_FinishSpawningActor_ReturnValue3' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, K2Node_CreateDelegate_OutputDelegate) == 0x0003B8, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, CallFunc_K2_GetActorLocation_ReturnValue5) == 0x0003C8, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::CallFunc_K2_GetActorLocation_ReturnValue5' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_ExecuteUbergraph_BluGloManager, CallFunc_MakeLiteralFloat_ReturnValue2) == 0x0003D4, "Member 'BluGloManager_C_ExecuteUbergraph_BluGloManager::CallFunc_MakeLiteralFloat_ReturnValue2' has a wrong offset!");

// Function BluGloManager.BluGloManager_C.StopSpawnFX
// 0x0001 (0x0001 - 0x0000)
struct BluGloManager_C_StopSpawnFX final
{
public:
	bool                                          off;                                               // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BluGloManager_C_StopSpawnFX) == 0x000001, "Wrong alignment on BluGloManager_C_StopSpawnFX");
static_assert(sizeof(BluGloManager_C_StopSpawnFX) == 0x000001, "Wrong size on BluGloManager_C_StopSpawnFX");
static_assert(offsetof(BluGloManager_C_StopSpawnFX, off) == 0x000000, "Member 'BluGloManager_C_StopSpawnFX::off' has a wrong offset!");

// Function BluGloManager.BluGloManager_C.HandleMissionEvent_RequestBluGloSpawnUseEQS
// 0x00D4 (0x00D4 - 0x0000)
struct BluGloManager_C_HandleMissionEvent_RequestBluGloSpawnUseEQS final
{
public:
	struct FGuid                                  MissionGuid;                                       // 0x0000(0x0010)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FGameplayTagContainer                  ObjectiveHandle;                                   // 0x0010(0x0018)(Parm)
	class UFortMissionEventParams*                Params_0;                                          // 0x0028(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          DO_NOT_USE_THIS_OR_VARIABLES_BELOW;                // 0x002C(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2D[0x3];                                       // 0x002D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                EventFocus;                                        // 0x0030(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	const class UDataAsset*                       EventContent;                                      // 0x0034(0x0004)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	class AActor*                                 EventInstigator;                                   // 0x0038(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	int32                                         GenericInt;                                        // 0x003C(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	float                                         GenericFloat;                                      // 0x0040(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	class FText                                   GenericText;                                       // 0x0044(0x000C)(ConstParm, Parm, OutParm, ReferenceParm)
	struct FGameplayTagContainer                  GameplayTags;                                      // 0x0050(0x0018)(Parm)
	struct FFortMissionEvent                      MissionEvent;                                      // 0x0068(0x006C)(ConstParm, Parm, OutParm, ReferenceParm)
};
static_assert(alignof(BluGloManager_C_HandleMissionEvent_RequestBluGloSpawnUseEQS) == 0x000004, "Wrong alignment on BluGloManager_C_HandleMissionEvent_RequestBluGloSpawnUseEQS");
static_assert(sizeof(BluGloManager_C_HandleMissionEvent_RequestBluGloSpawnUseEQS) == 0x0000D4, "Wrong size on BluGloManager_C_HandleMissionEvent_RequestBluGloSpawnUseEQS");
static_assert(offsetof(BluGloManager_C_HandleMissionEvent_RequestBluGloSpawnUseEQS, MissionGuid) == 0x000000, "Member 'BluGloManager_C_HandleMissionEvent_RequestBluGloSpawnUseEQS::MissionGuid' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_HandleMissionEvent_RequestBluGloSpawnUseEQS, ObjectiveHandle) == 0x000010, "Member 'BluGloManager_C_HandleMissionEvent_RequestBluGloSpawnUseEQS::ObjectiveHandle' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_HandleMissionEvent_RequestBluGloSpawnUseEQS, Params_0) == 0x000028, "Member 'BluGloManager_C_HandleMissionEvent_RequestBluGloSpawnUseEQS::Params_0' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_HandleMissionEvent_RequestBluGloSpawnUseEQS, DO_NOT_USE_THIS_OR_VARIABLES_BELOW) == 0x00002C, "Member 'BluGloManager_C_HandleMissionEvent_RequestBluGloSpawnUseEQS::DO_NOT_USE_THIS_OR_VARIABLES_BELOW' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_HandleMissionEvent_RequestBluGloSpawnUseEQS, EventFocus) == 0x000030, "Member 'BluGloManager_C_HandleMissionEvent_RequestBluGloSpawnUseEQS::EventFocus' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_HandleMissionEvent_RequestBluGloSpawnUseEQS, EventContent) == 0x000034, "Member 'BluGloManager_C_HandleMissionEvent_RequestBluGloSpawnUseEQS::EventContent' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_HandleMissionEvent_RequestBluGloSpawnUseEQS, EventInstigator) == 0x000038, "Member 'BluGloManager_C_HandleMissionEvent_RequestBluGloSpawnUseEQS::EventInstigator' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_HandleMissionEvent_RequestBluGloSpawnUseEQS, GenericInt) == 0x00003C, "Member 'BluGloManager_C_HandleMissionEvent_RequestBluGloSpawnUseEQS::GenericInt' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_HandleMissionEvent_RequestBluGloSpawnUseEQS, GenericFloat) == 0x000040, "Member 'BluGloManager_C_HandleMissionEvent_RequestBluGloSpawnUseEQS::GenericFloat' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_HandleMissionEvent_RequestBluGloSpawnUseEQS, GenericText) == 0x000044, "Member 'BluGloManager_C_HandleMissionEvent_RequestBluGloSpawnUseEQS::GenericText' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_HandleMissionEvent_RequestBluGloSpawnUseEQS, GameplayTags) == 0x000050, "Member 'BluGloManager_C_HandleMissionEvent_RequestBluGloSpawnUseEQS::GameplayTags' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_HandleMissionEvent_RequestBluGloSpawnUseEQS, MissionEvent) == 0x000068, "Member 'BluGloManager_C_HandleMissionEvent_RequestBluGloSpawnUseEQS::MissionEvent' has a wrong offset!");

// Function BluGloManager.BluGloManager_C.EQSQueryFinished
// 0x0008 (0x0008 - 0x0000)
struct BluGloManager_C_EQSQueryFinished final
{
public:
	class UEnvQueryInstanceBlueprintWrapper*      QueryInstance;                                     // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	EEnvQueryStatus                               QueryStatus;                                       // 0x0004(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BluGloManager_C_EQSQueryFinished) == 0x000004, "Wrong alignment on BluGloManager_C_EQSQueryFinished");
static_assert(sizeof(BluGloManager_C_EQSQueryFinished) == 0x000008, "Wrong size on BluGloManager_C_EQSQueryFinished");
static_assert(offsetof(BluGloManager_C_EQSQueryFinished, QueryInstance) == 0x000000, "Member 'BluGloManager_C_EQSQueryFinished::QueryInstance' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_EQSQueryFinished, QueryStatus) == 0x000004, "Member 'BluGloManager_C_EQSQueryFinished::QueryStatus' has a wrong offset!");

// Function BluGloManager.BluGloManager_C.HandleMissionEvent_RequestBluGloSpawnUseActor
// 0x00D4 (0x00D4 - 0x0000)
struct BluGloManager_C_HandleMissionEvent_RequestBluGloSpawnUseActor final
{
public:
	struct FGuid                                  MissionGuid;                                       // 0x0000(0x0010)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FGameplayTagContainer                  ObjectiveHandle;                                   // 0x0010(0x0018)(Parm)
	class UFortMissionEventParams*                Params_0;                                          // 0x0028(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          DO_NOT_USE_THIS_OR_VARIABLES_BELOW;                // 0x002C(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2D[0x3];                                       // 0x002D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                EventFocus;                                        // 0x0030(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	const class UDataAsset*                       EventContent;                                      // 0x0034(0x0004)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	class AActor*                                 EventInstigator;                                   // 0x0038(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	int32                                         GenericInt;                                        // 0x003C(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	float                                         GenericFloat;                                      // 0x0040(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	class FText                                   GenericText;                                       // 0x0044(0x000C)(ConstParm, Parm, OutParm, ReferenceParm)
	struct FGameplayTagContainer                  GameplayTags;                                      // 0x0050(0x0018)(Parm)
	struct FFortMissionEvent                      MissionEvent;                                      // 0x0068(0x006C)(ConstParm, Parm, OutParm, ReferenceParm)
};
static_assert(alignof(BluGloManager_C_HandleMissionEvent_RequestBluGloSpawnUseActor) == 0x000004, "Wrong alignment on BluGloManager_C_HandleMissionEvent_RequestBluGloSpawnUseActor");
static_assert(sizeof(BluGloManager_C_HandleMissionEvent_RequestBluGloSpawnUseActor) == 0x0000D4, "Wrong size on BluGloManager_C_HandleMissionEvent_RequestBluGloSpawnUseActor");
static_assert(offsetof(BluGloManager_C_HandleMissionEvent_RequestBluGloSpawnUseActor, MissionGuid) == 0x000000, "Member 'BluGloManager_C_HandleMissionEvent_RequestBluGloSpawnUseActor::MissionGuid' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_HandleMissionEvent_RequestBluGloSpawnUseActor, ObjectiveHandle) == 0x000010, "Member 'BluGloManager_C_HandleMissionEvent_RequestBluGloSpawnUseActor::ObjectiveHandle' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_HandleMissionEvent_RequestBluGloSpawnUseActor, Params_0) == 0x000028, "Member 'BluGloManager_C_HandleMissionEvent_RequestBluGloSpawnUseActor::Params_0' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_HandleMissionEvent_RequestBluGloSpawnUseActor, DO_NOT_USE_THIS_OR_VARIABLES_BELOW) == 0x00002C, "Member 'BluGloManager_C_HandleMissionEvent_RequestBluGloSpawnUseActor::DO_NOT_USE_THIS_OR_VARIABLES_BELOW' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_HandleMissionEvent_RequestBluGloSpawnUseActor, EventFocus) == 0x000030, "Member 'BluGloManager_C_HandleMissionEvent_RequestBluGloSpawnUseActor::EventFocus' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_HandleMissionEvent_RequestBluGloSpawnUseActor, EventContent) == 0x000034, "Member 'BluGloManager_C_HandleMissionEvent_RequestBluGloSpawnUseActor::EventContent' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_HandleMissionEvent_RequestBluGloSpawnUseActor, EventInstigator) == 0x000038, "Member 'BluGloManager_C_HandleMissionEvent_RequestBluGloSpawnUseActor::EventInstigator' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_HandleMissionEvent_RequestBluGloSpawnUseActor, GenericInt) == 0x00003C, "Member 'BluGloManager_C_HandleMissionEvent_RequestBluGloSpawnUseActor::GenericInt' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_HandleMissionEvent_RequestBluGloSpawnUseActor, GenericFloat) == 0x000040, "Member 'BluGloManager_C_HandleMissionEvent_RequestBluGloSpawnUseActor::GenericFloat' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_HandleMissionEvent_RequestBluGloSpawnUseActor, GenericText) == 0x000044, "Member 'BluGloManager_C_HandleMissionEvent_RequestBluGloSpawnUseActor::GenericText' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_HandleMissionEvent_RequestBluGloSpawnUseActor, GameplayTags) == 0x000050, "Member 'BluGloManager_C_HandleMissionEvent_RequestBluGloSpawnUseActor::GameplayTags' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_HandleMissionEvent_RequestBluGloSpawnUseActor, MissionEvent) == 0x000068, "Member 'BluGloManager_C_HandleMissionEvent_RequestBluGloSpawnUseActor::MissionEvent' has a wrong offset!");

// Function BluGloManager.BluGloManager_C.BlueprintHandleMissionEventNoReply
// 0x006C (0x006C - 0x0000)
struct BluGloManager_C_BlueprintHandleMissionEventNoReply final
{
public:
	struct FFortMissionEvent                      MissionEvent;                                      // 0x0000(0x006C)(ConstParm, Parm, OutParm, ReferenceParm)
};
static_assert(alignof(BluGloManager_C_BlueprintHandleMissionEventNoReply) == 0x000004, "Wrong alignment on BluGloManager_C_BlueprintHandleMissionEventNoReply");
static_assert(sizeof(BluGloManager_C_BlueprintHandleMissionEventNoReply) == 0x00006C, "Wrong size on BluGloManager_C_BlueprintHandleMissionEventNoReply");
static_assert(offsetof(BluGloManager_C_BlueprintHandleMissionEventNoReply, MissionEvent) == 0x000000, "Member 'BluGloManager_C_BlueprintHandleMissionEventNoReply::MissionEvent' has a wrong offset!");

// Function BluGloManager.BluGloManager_C.RequestedBluGo
// 0x001C (0x001C - 0x0000)
struct BluGloManager_C_RequestedBluGo final
{
public:
	class AFortMission*                           Mission;                                           // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                EQS_Start_Location;                                // 0x0004(0x000C)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	class AActor*                                 Actor;                                             // 0x0010(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0014(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_15[0x3];                                       // 0x0015(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_GetCurrentBluGloRewards_ReturnValue;      // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BluGloManager_C_RequestedBluGo) == 0x000004, "Wrong alignment on BluGloManager_C_RequestedBluGo");
static_assert(sizeof(BluGloManager_C_RequestedBluGo) == 0x00001C, "Wrong size on BluGloManager_C_RequestedBluGo");
static_assert(offsetof(BluGloManager_C_RequestedBluGo, Mission) == 0x000000, "Member 'BluGloManager_C_RequestedBluGo::Mission' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_RequestedBluGo, EQS_Start_Location) == 0x000004, "Member 'BluGloManager_C_RequestedBluGo::EQS_Start_Location' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_RequestedBluGo, Actor) == 0x000010, "Member 'BluGloManager_C_RequestedBluGo::Actor' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_RequestedBluGo, CallFunc_IsValid_ReturnValue) == 0x000014, "Member 'BluGloManager_C_RequestedBluGo::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_RequestedBluGo, CallFunc_GetCurrentBluGloRewards_ReturnValue) == 0x000018, "Member 'BluGloManager_C_RequestedBluGo::CallFunc_GetCurrentBluGloRewards_ReturnValue' has a wrong offset!");

// Function BluGloManager.BluGloManager_C.RemoveOccupiedNodes
// 0x001C (0x001C - 0x0000)
struct BluGloManager_C_RemoveOccupiedNodes final
{
public:
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	class ATiered_BluGlo_Parent_C*                CallFunc_Array_Get_Item;                           // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Array_RemoveItem_ReturnValue;             // 0x000C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_D[0x3];                                        // 0x000D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0014(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_15[0x3];                                       // 0x0015(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BluGloManager_C_RemoveOccupiedNodes) == 0x000004, "Wrong alignment on BluGloManager_C_RemoveOccupiedNodes");
static_assert(sizeof(BluGloManager_C_RemoveOccupiedNodes) == 0x00001C, "Wrong size on BluGloManager_C_RemoveOccupiedNodes");
static_assert(offsetof(BluGloManager_C_RemoveOccupiedNodes, Temp_int_Array_Index_Variable) == 0x000000, "Member 'BluGloManager_C_RemoveOccupiedNodes::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_RemoveOccupiedNodes, CallFunc_Array_Get_Item) == 0x000004, "Member 'BluGloManager_C_RemoveOccupiedNodes::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_RemoveOccupiedNodes, CallFunc_Array_Length_ReturnValue) == 0x000008, "Member 'BluGloManager_C_RemoveOccupiedNodes::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_RemoveOccupiedNodes, CallFunc_Array_RemoveItem_ReturnValue) == 0x00000C, "Member 'BluGloManager_C_RemoveOccupiedNodes::CallFunc_Array_RemoveItem_ReturnValue' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_RemoveOccupiedNodes, Temp_int_Loop_Counter_Variable) == 0x000010, "Member 'BluGloManager_C_RemoveOccupiedNodes::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_RemoveOccupiedNodes, CallFunc_Less_IntInt_ReturnValue) == 0x000014, "Member 'BluGloManager_C_RemoveOccupiedNodes::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BluGloManager_C_RemoveOccupiedNodes, CallFunc_Add_IntInt_ReturnValue) == 0x000018, "Member 'BluGloManager_C_RemoveOccupiedNodes::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");

}

#pragma pack(pop)
