#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BrickSimple_Roof_Peak_Cap

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


#pragma pack(push, 0x4)
namespace SDK
{

// BlueprintGeneratedClass BrickSimple_Roof_Peak_Cap.BrickSimple_Roof_Peak_Cap_C
// 0x0000 (0x09F0 - 0x09F0)
class ABrickSimple_Roof_Peak_Cap_C final : public ABuildingWall
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BrickSimple_Roof_Peak_Cap_C">();
	}
	static class ABrickSimple_Roof_Peak_Cap_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABrickSimple_Roof_Peak_Cap_C>();
	}
};
static_assert(alignof(ABrickSimple_Roof_Peak_Cap_C) == 0x000004, "Wrong alignment on ABrickSimple_Roof_Peak_Cap_C");
static_assert(sizeof(ABrickSimple_Roof_Peak_Cap_C) == 0x0009F0, "Wrong size on ABrickSimple_Roof_Peak_Cap_C");

}

#pragma pack(pop)
