#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DoorMetaObstacle

#include "Basic.hpp"

#include "Engine_classes.hpp"


#pragma pack(push, 0x4)
namespace SDK
{

// BlueprintGeneratedClass DoorMetaObstacle.DoorMetaObstacle_C
// 0x0000 (0x0074 - 0x0074)
class UDoorMetaObstacle_C final : public UNavAreaMeta_SwitchByAgent
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"DoorMetaObstacle_C">();
	}
	static class UDoorMetaObstacle_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDoorMetaObstacle_C>();
	}
};
static_assert(alignof(UDoorMetaObstacle_C) == 0x000004, "Wrong alignment on UDoorMetaObstacle_C");
static_assert(sizeof(UDoorMetaObstacle_C) == 0x000074, "Wrong size on UDoorMetaObstacle_C");

}

#pragma pack(pop)
