#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Factory_Trim_19a

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


#pragma pack(push, 0x4)
namespace SDK
{

// BlueprintGeneratedClass Factory_Trim_19a.Factory_Trim_19a_C
// 0x0000 (0x094C - 0x094C)
class AFactory_Trim_19a_C final : public ABuildingPropWall
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Factory_Trim_19a_C">();
	}
	static class AFactory_Trim_19a_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AFactory_Trim_19a_C>();
	}
};
static_assert(alignof(AFactory_Trim_19a_C) == 0x000004, "Wrong alignment on AFactory_Trim_19a_C");
static_assert(sizeof(AFactory_Trim_19a_C) == 0x00094C, "Wrong size on AFactory_Trim_19a_C");

}

#pragma pack(pop)
