#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Trap_RailTurret

#include "Basic.hpp"

#include "GA_Trap_RailTurret_classes.hpp"
#include "GA_Trap_RailTurret_parameters.hpp"


#pragma pack(push, 0x4)
namespace SDK
{

// Function GA_Trap_RailTurret.GA_Trap_RailTurret_C.ExecuteUbergraph_GA_Trap_RailTurret
// (HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UGA_Trap_RailTurret_C::ExecuteUbergraph_GA_Trap_RailTurret(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Trap_RailTurret_C", "ExecuteUbergraph_GA_Trap_RailTurret");

	Params::GA_Trap_RailTurret_C_ExecuteUbergraph_GA_Trap_RailTurret Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Trap_RailTurret.GA_Trap_RailTurret_C.K2_ActivateAbility
// (Event, Protected, BlueprintEvent)

void UGA_Trap_RailTurret_C::K2_ActivateAbility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Trap_RailTurret_C", "K2_ActivateAbility");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Trap_RailTurret.GA_Trap_RailTurret_C.Targeted_DF598E9A4A91186F4A43BC9986F864A0
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGameplayAbilityTargetDataHandle&TargetData                                             (ConstParm, Parm, OutParm, ReferenceParm)
// const struct FGameplayTag&              ApplicationTag                                         (Parm)

void UGA_Trap_RailTurret_C::Targeted_DF598E9A4A91186F4A43BC9986F864A0(const struct FGameplayAbilityTargetDataHandle& TargetData, const struct FGameplayTag& ApplicationTag)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Trap_RailTurret_C", "Targeted_DF598E9A4A91186F4A43BC9986F864A0");

	Params::GA_Trap_RailTurret_C_Targeted_DF598E9A4A91186F4A43BC9986F864A0 Parms{};

	Parms.TargetData = std::move(TargetData);
	Parms.ApplicationTag = std::move(ApplicationTag);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Trap_RailTurret.GA_Trap_RailTurret_C.Cancelled_DF598E9A4A91186F4A43BC9986F864A0
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGameplayAbilityTargetDataHandle&TargetData                                             (ConstParm, Parm, OutParm, ReferenceParm)
// const struct FGameplayTag&              ApplicationTag                                         (Parm)

void UGA_Trap_RailTurret_C::Cancelled_DF598E9A4A91186F4A43BC9986F864A0(const struct FGameplayAbilityTargetDataHandle& TargetData, const struct FGameplayTag& ApplicationTag)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Trap_RailTurret_C", "Cancelled_DF598E9A4A91186F4A43BC9986F864A0");

	Params::GA_Trap_RailTurret_C_Cancelled_DF598E9A4A91186F4A43BC9986F864A0 Parms{};

	Parms.TargetData = std::move(TargetData);
	Parms.ApplicationTag = std::move(ApplicationTag);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Trap_RailTurret.GA_Trap_RailTurret_C.HasValidTarget
// (Private, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool*                                   ValidTarget                                            (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UGA_Trap_RailTurret_C::HasValidTarget(bool* ValidTarget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Trap_RailTurret_C", "HasValidTarget");

	Params::GA_Trap_RailTurret_C_HasValidTarget Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (ValidTarget != nullptr)
		*ValidTarget = Parms.ValidTarget;
}


// Function GA_Trap_RailTurret.GA_Trap_RailTurret_C.Fire
// (Private, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AFortPawn*                        Enemy                                                  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class ABuildingTrap*                    ThisTrap                                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UGA_Trap_RailTurret_C::Fire(class AFortPawn* Enemy, class ABuildingTrap* ThisTrap)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Trap_RailTurret_C", "Fire");

	Params::GA_Trap_RailTurret_C_Fire Parms{};

	Parms.Enemy = Enemy;
	Parms.ThisTrap = ThisTrap;

	UObject::ProcessEvent(Func, &Parms);
}

}

#pragma pack(pop)
