#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GAB_HuskPitcherCeilingMelee

#include "Basic.hpp"

#include "GAB_HuskCeilingMelee_classes.hpp"


#pragma pack(push, 0x4)
namespace SDK
{

// GameplayAbilityBlueprintGeneratedClass GAB_HuskPitcherCeilingMelee.GAB_HuskPitcherCeilingMelee_C
// 0x0000 (0x06EC - 0x06EC)
class UGAB_HuskPitcherCeilingMelee_C final : public UGAB_HuskCeilingMelee_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GAB_HuskPitcherCeilingMelee_C">();
	}
	static class UGAB_HuskPitcherCeilingMelee_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGAB_HuskPitcherCeilingMelee_C>();
	}
};
static_assert(alignof(UGAB_HuskPitcherCeilingMelee_C) == 0x000004, "Wrong alignment on UGAB_HuskPitcherCeilingMelee_C");
static_assert(sizeof(UGAB_HuskPitcherCeilingMelee_C) == 0x0006EC, "Wrong size on UGAB_HuskPitcherCeilingMelee_C");

}

#pragma pack(pop)
