#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GAB_SmasherRoarRampage

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GAB_AIBaseSimpleMontage_classes.hpp"


#pragma pack(push, 0x4)
namespace SDK
{

// GameplayAbilityBlueprintGeneratedClass GAB_SmasherRoarRampage.GAB_SmasherRoarRampage_C
// 0x0008 (0x06E8 - 0x06E0)
class UGAB_SmasherRoarRampage_C final : public UGAB_AIBaseSimpleMontage_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_GAB_SmasherRoarRampage_C;           // 0x06E0(0x0004)(ZeroConstructor, Transient, DuplicateTransient)
	class UAnimMontage*                           M_Roar;                                            // 0x06E4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_GAB_SmasherRoarRampage(int32 EntryPoint);
	void MoveToLoop();
	void K2_ActivateAbility();
	void OnComplete_54C8E8064FCFF7F4A70F659701F57F44();
	void OnInterrupted_54C8E8064FCFF7F4A70F659701F57F44();
	void OnCancelled_54C8E8064FCFF7F4A70F659701F57F44();
	void OnComplete_40798A2B441E91DC8E110D93DD495C5C();
	void OnInterrupted_40798A2B441E91DC8E110D93DD495C5C();
	void OnCancelled_40798A2B441E91DC8E110D93DD495C5C();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GAB_SmasherRoarRampage_C">();
	}
	static class UGAB_SmasherRoarRampage_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGAB_SmasherRoarRampage_C>();
	}
};
static_assert(alignof(UGAB_SmasherRoarRampage_C) == 0x000004, "Wrong alignment on UGAB_SmasherRoarRampage_C");
static_assert(sizeof(UGAB_SmasherRoarRampage_C) == 0x0006E8, "Wrong size on UGAB_SmasherRoarRampage_C");
static_assert(offsetof(UGAB_SmasherRoarRampage_C, UberGraphFrame_GAB_SmasherRoarRampage_C) == 0x0006E0, "Member 'UGAB_SmasherRoarRampage_C::UberGraphFrame_GAB_SmasherRoarRampage_C' has a wrong offset!");
static_assert(offsetof(UGAB_SmasherRoarRampage_C, M_Roar) == 0x0006E4, "Member 'UGAB_SmasherRoarRampage_C::M_Roar' has a wrong offset!");

}

#pragma pack(pop)
