#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_NPC_PawnFireDamageEffect

#include "Basic.hpp"

#include "GET_PeriodicFireDamage_classes.hpp"


#pragma pack(push, 0x4)
namespace SDK
{

// BlueprintGeneratedClass GE_NPC_PawnFireDamageEffect.GE_NPC_PawnFireDamageEffect_C
// 0x0000 (0x0368 - 0x0368)
class UGE_NPC_PawnFireDamageEffect_C final : public UGET_PeriodicFireDamage_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_NPC_PawnFireDamageEffect_C">();
	}
	static class UGE_NPC_PawnFireDamageEffect_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_NPC_PawnFireDamageEffect_C>();
	}
};
static_assert(alignof(UGE_NPC_PawnFireDamageEffect_C) == 0x000004, "Wrong alignment on UGE_NPC_PawnFireDamageEffect_C");
static_assert(sizeof(UGE_NPC_PawnFireDamageEffect_C) == 0x000368, "Wrong size on UGE_NPC_PawnFireDamageEffect_C");

}

#pragma pack(pop)
