#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_SmasherRadialMeleeDamageRampage_Child

#include "Basic.hpp"

#include "GE_SmasherRadialMeleeDamage_classes.hpp"


#pragma pack(push, 0x4)
namespace SDK
{

// BlueprintGeneratedClass GE_SmasherRadialMeleeDamageRampage_Child.GE_SmasherRadialMeleeDamageRampage_Child_C
// 0x0000 (0x0368 - 0x0368)
class UGE_SmasherRadialMeleeDamageRampage_Child_C final : public UGE_SmasherRadialMeleeDamage_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_SmasherRadialMeleeDamageRampage_Child_C">();
	}
	static class UGE_SmasherRadialMeleeDamageRampage_Child_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_SmasherRadialMeleeDamageRampage_Child_C>();
	}
};
static_assert(alignof(UGE_SmasherRadialMeleeDamageRampage_Child_C) == 0x000004, "Wrong alignment on UGE_SmasherRadialMeleeDamageRampage_Child_C");
static_assert(sizeof(UGE_SmasherRadialMeleeDamageRampage_Child_C) == 0x000368, "Wrong size on UGE_SmasherRadialMeleeDamageRampage_Child_C");

}

#pragma pack(pop)
