#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GET_DirectIceDamage

#include "Basic.hpp"

#include "GET_DirectElementalDamage_classes.hpp"


#pragma pack(push, 0x4)
namespace SDK
{

// BlueprintGeneratedClass GET_DirectIceDamage.GET_DirectIceDamage_C
// 0x0000 (0x0368 - 0x0368)
class UGET_DirectIceDamage_C : public UGET_DirectElementalDamage_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GET_DirectIceDamage_C">();
	}
	static class UGET_DirectIceDamage_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGET_DirectIceDamage_C>();
	}
};
static_assert(alignof(UGET_DirectIceDamage_C) == 0x000004, "Wrong alignment on UGET_DirectIceDamage_C");
static_assert(sizeof(UGET_DirectIceDamage_C) == 0x000368, "Wrong size on UGET_DirectIceDamage_C");

}

#pragma pack(pop)
