#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HuskPawn_Lightning

#include "Basic.hpp"

#include "HuskPawn_classes.hpp"


#pragma pack(push, 0x4)
namespace SDK
{

// BlueprintGeneratedClass HuskPawn_Lightning.HuskPawn_Lightning_C
// 0x0000 (0x1080 - 0x1080)
class AHuskPawn_Lightning_C final : public AHuskPawn_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"HuskPawn_Lightning_C">();
	}
	static class AHuskPawn_Lightning_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AHuskPawn_Lightning_C>();
	}
};
static_assert(alignof(AHuskPawn_Lightning_C) == 0x000010, "Wrong alignment on AHuskPawn_Lightning_C");
static_assert(sizeof(AHuskPawn_Lightning_C) == 0x001080, "Wrong size on AHuskPawn_Lightning_C");

}

#pragma pack(pop)
