#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HuskInterface

#include "Basic.hpp"

#include "HuskInterface_classes.hpp"
#include "HuskInterface_parameters.hpp"


#pragma pack(push, 0x4)
namespace SDK
{

// Function HuskInterface.HuskInterface_C.IgnitePropaneTank
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AFortPawn*                        Pawn                                                   (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// float                                   RemainingFuseTime                                      (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    JustDrop                                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void IHuskInterface_C::IgnitePropaneTank(class AFortPawn* Pawn, float RemainingFuseTime, bool JustDrop)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HuskInterface_C", "IgnitePropaneTank");

	Params::HuskInterface_C_IgnitePropaneTank Parms{};

	Parms.Pawn = Pawn;
	Parms.RemainingFuseTime = RemainingFuseTime;
	Parms.JustDrop = JustDrop;

	UObject::ProcessEvent(Func, &Parms);
}


// Function HuskInterface.HuskInterface_C.FSMRemovePropaneTank
// (Public, BlueprintCallable, BlueprintEvent)

void IHuskInterface_C::FSMRemovePropaneTank()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HuskInterface_C", "FSMRemovePropaneTank");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HuskInterface.HuskInterface_C.FSMFailedToSpawnTank
// (Public, BlueprintCallable, BlueprintEvent)

void IHuskInterface_C::FSMFailedToSpawnTank()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HuskInterface_C", "FSMFailedToSpawnTank");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HuskInterface.HuskInterface_C.FSMBeginPropaneTankMelee
// (Public, BlueprintCallable, BlueprintEvent)

void IHuskInterface_C::FSMBeginPropaneTankMelee()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HuskInterface_C", "FSMBeginPropaneTankMelee");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HuskInterface.HuskInterface_C.BeeCloudDespawned
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AFortProjectileBase*              Cloud                                                  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void IHuskInterface_C::BeeCloudDespawned(class AFortProjectileBase* Cloud)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HuskInterface_C", "BeeCloudDespawned");

	Params::HuskInterface_C_BeeCloudDespawned Parms{};

	Parms.Cloud = Cloud;

	UObject::ProcessEvent(Func, &Parms);
}


// Function HuskInterface.HuskInterface_C.ManageBurpEffect
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Enabled                                                (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void IHuskInterface_C::ManageBurpEffect(bool Enabled)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HuskInterface_C", "ManageBurpEffect");

	Params::HuskInterface_C_ManageBurpEffect Parms{};

	Parms.Enabled = Enabled;

	UObject::ProcessEvent(Func, &Parms);
}

}

#pragma pack(pop)
