#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: InGame_Actor

#include "Basic.hpp"

#include "InGame_Actor_classes.hpp"
#include "InGame_Actor_parameters.hpp"


#pragma pack(push, 0x4)
namespace SDK
{

// Function InGame_Actor.InGame_Actor_C.ExecuteUbergraph_InGame_Actor
// (HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AInGame_Actor_C::ExecuteUbergraph_InGame_Actor(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("InGame_Actor_C", "ExecuteUbergraph_InGame_Actor");

	Params::InGame_Actor_C_ExecuteUbergraph_InGame_Actor Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function InGame_Actor.InGame_Actor_C.EquipBuildingWall
// (BlueprintCallable, BlueprintEvent)

void AInGame_Actor_C::EquipBuildingWall()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("InGame_Actor_C", "EquipBuildingWall");

	UObject::ProcessEvent(Func, nullptr);
}


// Function InGame_Actor.InGame_Actor_C.EquipBuildingRoof
// (BlueprintCallable, BlueprintEvent)

void AInGame_Actor_C::EquipBuildingRoof()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("InGame_Actor_C", "EquipBuildingRoof");

	UObject::ProcessEvent(Func, nullptr);
}


// Function InGame_Actor.InGame_Actor_C.EquipBuildingFloor
// (BlueprintCallable, BlueprintEvent)

void AInGame_Actor_C::EquipBuildingFloor()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("InGame_Actor_C", "EquipBuildingFloor");

	UObject::ProcessEvent(Func, nullptr);
}


// Function InGame_Actor.InGame_Actor_C.Inventory
// (BlueprintCallable, BlueprintEvent)

void AInGame_Actor_C::Inventory()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("InGame_Actor_C", "Inventory");

	UObject::ProcessEvent(Func, nullptr);
}


// Function InGame_Actor.InGame_Actor_C.SpawnBuildingPreviews
// (BlueprintCallable, BlueprintEvent)

void AInGame_Actor_C::SpawnBuildingPreviews()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("InGame_Actor_C", "SpawnBuildingPreviews");

	UObject::ProcessEvent(Func, nullptr);
}


// Function InGame_Actor.InGame_Actor_C.ReceiveBeginPlay
// (Event, Public, BlueprintEvent)

void AInGame_Actor_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("InGame_Actor_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function InGame_Actor.InGame_Actor_C.EquipBuildingStair
// (BlueprintCallable, BlueprintEvent)

void AInGame_Actor_C::EquipBuildingStair()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("InGame_Actor_C", "EquipBuildingStair");

	UObject::ProcessEvent(Func, nullptr);
}


// Function InGame_Actor.InGame_Actor_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AInGame_Actor_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("InGame_Actor_C", "ReceiveTick");

	Params::InGame_Actor_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function InGame_Actor.InGame_Actor_C.Spawn Pickup
// (NetReliable, BlueprintCallable, BlueprintEvent)

void AInGame_Actor_C::Spawn_Pickup()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("InGame_Actor_C", "Spawn Pickup");

	UObject::ProcessEvent(Func, nullptr);
}


// Function InGame_Actor.InGame_Actor_C.UpdateInventory
// (NetReliable, BlueprintCallable, BlueprintEvent)

void AInGame_Actor_C::UpdateInventory()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("InGame_Actor_C", "UpdateInventory");

	UObject::ProcessEvent(Func, nullptr);
}


// Function InGame_Actor.InGame_Actor_C.QuickBars
// (NetReliable, BlueprintCallable, BlueprintEvent)

void AInGame_Actor_C::QuickBars()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("InGame_Actor_C", "QuickBars");

	UObject::ProcessEvent(Func, nullptr);
}


// Function InGame_Actor.InGame_Actor_C.Add GameplayEffects
// (NetReliable, BlueprintCallable, BlueprintEvent)

void AInGame_Actor_C::Add_GameplayEffects()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("InGame_Actor_C", "Add GameplayEffects");

	UObject::ProcessEvent(Func, nullptr);
}


// Function InGame_Actor.InGame_Actor_C.SpawnPlayer
// (NetReliable, BlueprintCallable, BlueprintEvent)

void AInGame_Actor_C::SpawnPlayer()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("InGame_Actor_C", "SpawnPlayer");

	UObject::ProcessEvent(Func, nullptr);
}


// Function InGame_Actor.InGame_Actor_C.InpActEvt_HotbarKey9_UniqueObjectNameForCooking_93
// (BlueprintEvent)
// Parameters:
// const struct FKey&                      Key                                                    (Parm)

void AInGame_Actor_C::InpActEvt_HotbarKey9_UniqueObjectNameForCooking_93(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("InGame_Actor_C", "InpActEvt_HotbarKey9_UniqueObjectNameForCooking_93");

	Params::InGame_Actor_C_InpActEvt_HotbarKey9_UniqueObjectNameForCooking_93 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function InGame_Actor.InGame_Actor_C.InpActEvt_SwitchQuickbar_UniqueObjectNameForCooking_94
// (BlueprintEvent)
// Parameters:
// const struct FKey&                      Key                                                    (Parm)

void AInGame_Actor_C::InpActEvt_SwitchQuickbar_UniqueObjectNameForCooking_94(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("InGame_Actor_C", "InpActEvt_SwitchQuickbar_UniqueObjectNameForCooking_94");

	Params::InGame_Actor_C_InpActEvt_SwitchQuickbar_UniqueObjectNameForCooking_94 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function InGame_Actor.InGame_Actor_C.InpActEvt_HotbarKey8_UniqueObjectNameForCooking_95
// (BlueprintEvent)
// Parameters:
// const struct FKey&                      Key                                                    (Parm)

void AInGame_Actor_C::InpActEvt_HotbarKey8_UniqueObjectNameForCooking_95(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("InGame_Actor_C", "InpActEvt_HotbarKey8_UniqueObjectNameForCooking_95");

	Params::InGame_Actor_C_InpActEvt_HotbarKey8_UniqueObjectNameForCooking_95 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function InGame_Actor.InGame_Actor_C.InpActEvt_HotbarKeyF7_UniqueObjectNameForCooking_96
// (BlueprintEvent)
// Parameters:
// const struct FKey&                      Key                                                    (Parm)

void AInGame_Actor_C::InpActEvt_HotbarKeyF7_UniqueObjectNameForCooking_96(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("InGame_Actor_C", "InpActEvt_HotbarKeyF7_UniqueObjectNameForCooking_96");

	Params::InGame_Actor_C_InpActEvt_HotbarKeyF7_UniqueObjectNameForCooking_96 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function InGame_Actor.InGame_Actor_C.InpActEvt_HotbarKeyF6_UniqueObjectNameForCooking_97
// (BlueprintEvent)
// Parameters:
// const struct FKey&                      Key                                                    (Parm)

void AInGame_Actor_C::InpActEvt_HotbarKeyF6_UniqueObjectNameForCooking_97(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("InGame_Actor_C", "InpActEvt_HotbarKeyF6_UniqueObjectNameForCooking_97");

	Params::InGame_Actor_C_InpActEvt_HotbarKeyF6_UniqueObjectNameForCooking_97 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function InGame_Actor.InGame_Actor_C.InpActEvt_HotbarKeyF5_UniqueObjectNameForCooking_98
// (BlueprintEvent)
// Parameters:
// const struct FKey&                      Key                                                    (Parm)

void AInGame_Actor_C::InpActEvt_HotbarKeyF5_UniqueObjectNameForCooking_98(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("InGame_Actor_C", "InpActEvt_HotbarKeyF5_UniqueObjectNameForCooking_98");

	Params::InGame_Actor_C_InpActEvt_HotbarKeyF5_UniqueObjectNameForCooking_98 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function InGame_Actor.InGame_Actor_C.InpActEvt_HotbarKeyF4_UniqueObjectNameForCooking_99
// (BlueprintEvent)
// Parameters:
// const struct FKey&                      Key                                                    (Parm)

void AInGame_Actor_C::InpActEvt_HotbarKeyF4_UniqueObjectNameForCooking_99(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("InGame_Actor_C", "InpActEvt_HotbarKeyF4_UniqueObjectNameForCooking_99");

	Params::InGame_Actor_C_InpActEvt_HotbarKeyF4_UniqueObjectNameForCooking_99 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function InGame_Actor.InGame_Actor_C.InpActEvt_HotbarKeyF3_UniqueObjectNameForCooking_100
// (BlueprintEvent)
// Parameters:
// const struct FKey&                      Key                                                    (Parm)

void AInGame_Actor_C::InpActEvt_HotbarKeyF3_UniqueObjectNameForCooking_100(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("InGame_Actor_C", "InpActEvt_HotbarKeyF3_UniqueObjectNameForCooking_100");

	Params::InGame_Actor_C_InpActEvt_HotbarKeyF3_UniqueObjectNameForCooking_100 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function InGame_Actor.InGame_Actor_C.InpActEvt_HotbarKeyF2_UniqueObjectNameForCooking_101
// (BlueprintEvent)
// Parameters:
// const struct FKey&                      Key                                                    (Parm)

void AInGame_Actor_C::InpActEvt_HotbarKeyF2_UniqueObjectNameForCooking_101(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("InGame_Actor_C", "InpActEvt_HotbarKeyF2_UniqueObjectNameForCooking_101");

	Params::InGame_Actor_C_InpActEvt_HotbarKeyF2_UniqueObjectNameForCooking_101 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function InGame_Actor.InGame_Actor_C.InpActEvt_HotbarKeyF1_UniqueObjectNameForCooking_102
// (BlueprintEvent)
// Parameters:
// const struct FKey&                      Key                                                    (Parm)

void AInGame_Actor_C::InpActEvt_HotbarKeyF1_UniqueObjectNameForCooking_102(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("InGame_Actor_C", "InpActEvt_HotbarKeyF1_UniqueObjectNameForCooking_102");

	Params::InGame_Actor_C_InpActEvt_HotbarKeyF1_UniqueObjectNameForCooking_102 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function InGame_Actor.InGame_Actor_C.InpActEvt_HotbarKey4_UniqueObjectNameForCooking_130
// (BlueprintEvent)
// Parameters:
// const struct FKey&                      Key                                                    (Parm)

void AInGame_Actor_C::InpActEvt_HotbarKey4_UniqueObjectNameForCooking_130(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("InGame_Actor_C", "InpActEvt_HotbarKey4_UniqueObjectNameForCooking_130");

	Params::InGame_Actor_C_InpActEvt_HotbarKey4_UniqueObjectNameForCooking_130 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function InGame_Actor.InGame_Actor_C.InpActEvt_HotbarKey3_UniqueObjectNameForCooking_131
// (BlueprintEvent)
// Parameters:
// const struct FKey&                      Key                                                    (Parm)

void AInGame_Actor_C::InpActEvt_HotbarKey3_UniqueObjectNameForCooking_131(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("InGame_Actor_C", "InpActEvt_HotbarKey3_UniqueObjectNameForCooking_131");

	Params::InGame_Actor_C_InpActEvt_HotbarKey3_UniqueObjectNameForCooking_131 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function InGame_Actor.InGame_Actor_C.InpActEvt_HotbarKey2_UniqueObjectNameForCooking_132
// (BlueprintEvent)
// Parameters:
// const struct FKey&                      Key                                                    (Parm)

void AInGame_Actor_C::InpActEvt_HotbarKey2_UniqueObjectNameForCooking_132(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("InGame_Actor_C", "InpActEvt_HotbarKey2_UniqueObjectNameForCooking_132");

	Params::InGame_Actor_C_InpActEvt_HotbarKey2_UniqueObjectNameForCooking_132 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function InGame_Actor.InGame_Actor_C.InpActEvt_HotbarKey1_UniqueObjectNameForCooking_133
// (BlueprintEvent)
// Parameters:
// const struct FKey&                      Key                                                    (Parm)

void AInGame_Actor_C::InpActEvt_HotbarKey1_UniqueObjectNameForCooking_133(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("InGame_Actor_C", "InpActEvt_HotbarKey1_UniqueObjectNameForCooking_133");

	Params::InGame_Actor_C_InpActEvt_HotbarKey1_UniqueObjectNameForCooking_133 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function InGame_Actor.InGame_Actor_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void AInGame_Actor_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("InGame_Actor_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function InGame_Actor.InGame_Actor_C.AddItemToInventory
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UFortItemDefinition*              ItemToAdd                                              (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class UFortWorldItem**                  Item                                                   (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AInGame_Actor_C::AddItemToInventory(class UFortItemDefinition* ItemToAdd, class UFortWorldItem** Item)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("InGame_Actor_C", "AddItemToInventory");

	Params::InGame_Actor_C_AddItemToInventory Parms{};

	Parms.ItemToAdd = ItemToAdd;

	UObject::ProcessEvent(Func, &Parms);

	if (Item != nullptr)
		*Item = Parms.Item;
}


// Function InGame_Actor.InGame_Actor_C.AddMainItemToInventory
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UFortItemDefinition*              ItemToAdd                                              (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// int32                                   Count                                                  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// const struct FGuid&                     Guid                                                   (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class UFortWorldItem**                  Item                                                   (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AInGame_Actor_C::AddMainItemToInventory(class UFortItemDefinition* ItemToAdd, int32 Count, const struct FGuid& Guid, class UFortWorldItem** Item)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("InGame_Actor_C", "AddMainItemToInventory");

	Params::InGame_Actor_C_AddMainItemToInventory Parms{};

	Parms.ItemToAdd = ItemToAdd;
	Parms.Count = Count;
	Parms.Guid = std::move(Guid);

	UObject::ProcessEvent(Func, &Parms);

	if (Item != nullptr)
		*Item = Parms.Item;
}

}

#pragma pack(pop)
