#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Mission_HuskHarvester

#include "Basic.hpp"

#include "Mission_HuskHarvester_classes.hpp"
#include "Mission_HuskHarvester_parameters.hpp"


#pragma pack(push, 0x4)
namespace SDK
{

// Function Mission_HuskHarvester.Mission_HuskHarvester_C.ExecuteUbergraph_Mission_HuskHarvester
// (HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AMission_HuskHarvester_C::ExecuteUbergraph_Mission_HuskHarvester(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Mission_HuskHarvester_C", "ExecuteUbergraph_Mission_HuskHarvester");

	Params::Mission_HuskHarvester_C_ExecuteUbergraph_Mission_HuskHarvester Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Mission_HuskHarvester.Mission_HuskHarvester_C.HandleMissionEvent_PlayersNotNearMachine
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGuid&                     MissionGuid_0                                          (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// const struct FGameplayTagContainer&     ObjectiveHandle                                        (Parm)
// class UFortMissionEventParams*          Params_0                                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    DO_NOT_USE_THIS_OR_VARIABLES_BELOW                     (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class UObject*                          EventFocus                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// const class UDataAsset*                 EventContent                                           (ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class AActor*                           EventInstigator                                        (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// int32                                   GenericInt                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// float                                   GenericFloat                                           (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// const class FText&                      GenericText                                            (ConstParm, Parm, OutParm, ReferenceParm)
// const struct FGameplayTagContainer&     GameplayTags                                           (Parm)
// const struct FFortMissionEvent&         MissionEvent                                           (ConstParm, Parm, OutParm, ReferenceParm)

void AMission_HuskHarvester_C::HandleMissionEvent_PlayersNotNearMachine(const struct FGuid& MissionGuid_0, const struct FGameplayTagContainer& ObjectiveHandle, class UFortMissionEventParams* Params_0, bool DO_NOT_USE_THIS_OR_VARIABLES_BELOW, class UObject* EventFocus, const class UDataAsset* EventContent, class AActor* EventInstigator, int32 GenericInt, float GenericFloat, const class FText& GenericText, const struct FGameplayTagContainer& GameplayTags, const struct FFortMissionEvent& MissionEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Mission_HuskHarvester_C", "HandleMissionEvent_PlayersNotNearMachine");

	Params::Mission_HuskHarvester_C_HandleMissionEvent_PlayersNotNearMachine Parms{};

	Parms.MissionGuid_0 = std::move(MissionGuid_0);
	Parms.ObjectiveHandle = std::move(ObjectiveHandle);
	Parms.Params_0 = Params_0;
	Parms.DO_NOT_USE_THIS_OR_VARIABLES_BELOW = DO_NOT_USE_THIS_OR_VARIABLES_BELOW;
	Parms.EventFocus = EventFocus;
	Parms.EventContent = EventContent;
	Parms.EventInstigator = EventInstigator;
	Parms.GenericInt = GenericInt;
	Parms.GenericFloat = GenericFloat;
	Parms.GenericText = std::move(GenericText);
	Parms.GameplayTags = std::move(GameplayTags);
	Parms.MissionEvent = std::move(MissionEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Mission_HuskHarvester.Mission_HuskHarvester_C.Event_GiveReward
// (BlueprintCallable, BlueprintEvent)

void AMission_HuskHarvester_C::Event_GiveReward()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Mission_HuskHarvester_C", "Event_GiveReward");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Mission_HuskHarvester.Mission_HuskHarvester_C.HandleMissionEvent_BluGloSpawner
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGuid&                     MissionGuid_0                                          (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// const struct FGameplayTagContainer&     ObjectiveHandle                                        (Parm)
// class UFortMissionEventParams*          Params_0                                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    DO_NOT_USE_THIS_OR_VARIABLES_BELOW                     (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class UObject*                          EventFocus                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// const class UDataAsset*                 EventContent                                           (ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class AActor*                           EventInstigator                                        (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// int32                                   GenericInt                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// float                                   GenericFloat                                           (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// const class FText&                      GenericText                                            (ConstParm, Parm, OutParm, ReferenceParm)
// const struct FGameplayTagContainer&     GameplayTags                                           (Parm)
// const struct FFortMissionEvent&         MissionEvent                                           (ConstParm, Parm, OutParm, ReferenceParm)

void AMission_HuskHarvester_C::HandleMissionEvent_BluGloSpawner(const struct FGuid& MissionGuid_0, const struct FGameplayTagContainer& ObjectiveHandle, class UFortMissionEventParams* Params_0, bool DO_NOT_USE_THIS_OR_VARIABLES_BELOW, class UObject* EventFocus, const class UDataAsset* EventContent, class AActor* EventInstigator, int32 GenericInt, float GenericFloat, const class FText& GenericText, const struct FGameplayTagContainer& GameplayTags, const struct FFortMissionEvent& MissionEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Mission_HuskHarvester_C", "HandleMissionEvent_BluGloSpawner");

	Params::Mission_HuskHarvester_C_HandleMissionEvent_BluGloSpawner Parms{};

	Parms.MissionGuid_0 = std::move(MissionGuid_0);
	Parms.ObjectiveHandle = std::move(ObjectiveHandle);
	Parms.Params_0 = Params_0;
	Parms.DO_NOT_USE_THIS_OR_VARIABLES_BELOW = DO_NOT_USE_THIS_OR_VARIABLES_BELOW;
	Parms.EventFocus = EventFocus;
	Parms.EventContent = EventContent;
	Parms.EventInstigator = EventInstigator;
	Parms.GenericInt = GenericInt;
	Parms.GenericFloat = GenericFloat;
	Parms.GenericText = std::move(GenericText);
	Parms.GameplayTags = std::move(GameplayTags);
	Parms.MissionEvent = std::move(MissionEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Mission_HuskHarvester.Mission_HuskHarvester_C.BlueprintOnActivated
// (BlueprintAuthorityOnly, Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FFortMissionEvent&         MissionEvent                                           (ConstParm, Parm, OutParm, ReferenceParm)

void AMission_HuskHarvester_C::BlueprintOnActivated(const struct FFortMissionEvent& MissionEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Mission_HuskHarvester_C", "BlueprintOnActivated");

	Params::Mission_HuskHarvester_C_BlueprintOnActivated Parms{};

	Parms.MissionEvent = std::move(MissionEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Mission_HuskHarvester.Mission_HuskHarvester_C.allenemieskilled
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UFortAIEncounterInfo*             Encounter                                              (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AMission_HuskHarvester_C::allenemieskilled(class UFortAIEncounterInfo* Encounter)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Mission_HuskHarvester_C", "allenemieskilled");

	Params::Mission_HuskHarvester_C_allenemieskilled Parms{};

	Parms.Encounter = Encounter;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Mission_HuskHarvester.Mission_HuskHarvester_C.StopEncounter1
// (BlueprintCallable, BlueprintEvent)

void AMission_HuskHarvester_C::StopEncounter1()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Mission_HuskHarvester_C", "StopEncounter1");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Mission_HuskHarvester.Mission_HuskHarvester_C.HandleMissionEvent_SpawnBluGlo
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGuid&                     MissionGuid_0                                          (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// const struct FGameplayTagContainer&     ObjectiveHandle                                        (Parm)
// class UFortMissionEventParams*          Params_0                                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    DO_NOT_USE_THIS_OR_VARIABLES_BELOW                     (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class UObject*                          EventFocus                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// const class UDataAsset*                 EventContent                                           (ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class AActor*                           EventInstigator                                        (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// int32                                   GenericInt                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// float                                   GenericFloat                                           (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// const class FText&                      GenericText                                            (ConstParm, Parm, OutParm, ReferenceParm)
// const struct FGameplayTagContainer&     GameplayTags                                           (Parm)
// const struct FFortMissionEvent&         MissionEvent                                           (ConstParm, Parm, OutParm, ReferenceParm)

void AMission_HuskHarvester_C::HandleMissionEvent_SpawnBluGlo(const struct FGuid& MissionGuid_0, const struct FGameplayTagContainer& ObjectiveHandle, class UFortMissionEventParams* Params_0, bool DO_NOT_USE_THIS_OR_VARIABLES_BELOW, class UObject* EventFocus, const class UDataAsset* EventContent, class AActor* EventInstigator, int32 GenericInt, float GenericFloat, const class FText& GenericText, const struct FGameplayTagContainer& GameplayTags, const struct FFortMissionEvent& MissionEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Mission_HuskHarvester_C", "HandleMissionEvent_SpawnBluGlo");

	Params::Mission_HuskHarvester_C_HandleMissionEvent_SpawnBluGlo Parms{};

	Parms.MissionGuid_0 = std::move(MissionGuid_0);
	Parms.ObjectiveHandle = std::move(ObjectiveHandle);
	Parms.Params_0 = Params_0;
	Parms.DO_NOT_USE_THIS_OR_VARIABLES_BELOW = DO_NOT_USE_THIS_OR_VARIABLES_BELOW;
	Parms.EventFocus = EventFocus;
	Parms.EventContent = EventContent;
	Parms.EventInstigator = EventInstigator;
	Parms.GenericInt = GenericInt;
	Parms.GenericFloat = GenericFloat;
	Parms.GenericText = std::move(GenericText);
	Parms.GameplayTags = std::move(GameplayTags);
	Parms.MissionEvent = std::move(MissionEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Mission_HuskHarvester.Mission_HuskHarvester_C.HandleMissionEvent_IsActivated
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGuid&                     MissionGuid_0                                          (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// const struct FGameplayTagContainer&     ObjectiveHandle                                        (Parm)
// class UFortMissionEventParams*          Params_0                                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    DO_NOT_USE_THIS_OR_VARIABLES_BELOW                     (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class UObject*                          EventFocus                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// const class UDataAsset*                 EventContent                                           (ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class AActor*                           EventInstigator                                        (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// int32                                   GenericInt                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// float                                   GenericFloat                                           (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// const class FText&                      GenericText                                            (ConstParm, Parm, OutParm, ReferenceParm)
// const struct FGameplayTagContainer&     GameplayTags                                           (Parm)
// const struct FFortMissionEvent&         MissionEvent                                           (ConstParm, Parm, OutParm, ReferenceParm)

void AMission_HuskHarvester_C::HandleMissionEvent_IsActivated(const struct FGuid& MissionGuid_0, const struct FGameplayTagContainer& ObjectiveHandle, class UFortMissionEventParams* Params_0, bool DO_NOT_USE_THIS_OR_VARIABLES_BELOW, class UObject* EventFocus, const class UDataAsset* EventContent, class AActor* EventInstigator, int32 GenericInt, float GenericFloat, const class FText& GenericText, const struct FGameplayTagContainer& GameplayTags, const struct FFortMissionEvent& MissionEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Mission_HuskHarvester_C", "HandleMissionEvent_IsActivated");

	Params::Mission_HuskHarvester_C_HandleMissionEvent_IsActivated Parms{};

	Parms.MissionGuid_0 = std::move(MissionGuid_0);
	Parms.ObjectiveHandle = std::move(ObjectiveHandle);
	Parms.Params_0 = Params_0;
	Parms.DO_NOT_USE_THIS_OR_VARIABLES_BELOW = DO_NOT_USE_THIS_OR_VARIABLES_BELOW;
	Parms.EventFocus = EventFocus;
	Parms.EventContent = EventContent;
	Parms.EventInstigator = EventInstigator;
	Parms.GenericInt = GenericInt;
	Parms.GenericFloat = GenericFloat;
	Parms.GenericText = std::move(GenericText);
	Parms.GameplayTags = std::move(GameplayTags);
	Parms.MissionEvent = std::move(MissionEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Mission_HuskHarvester.Mission_HuskHarvester_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void AMission_HuskHarvester_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Mission_HuskHarvester_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

#pragma pack(pop)
