#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NavLink_BalconyS

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


#pragma pack(push, 0x4)
namespace SDK
{

// BlueprintGeneratedClass NavLink_BalconyS.NavLink_BalconyS_C
// 0x0000 (0x005C - 0x005C)
class UNavLink_BalconyS_C final : public UFortNavLinkDefinition
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"NavLink_BalconyS_C">();
	}
	static class UNavLink_BalconyS_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UNavLink_BalconyS_C>();
	}
};
static_assert(alignof(UNavLink_BalconyS_C) == 0x000004, "Wrong alignment on UNavLink_BalconyS_C");
static_assert(sizeof(UNavLink_BalconyS_C) == 0x00005C, "Wrong size on UNavLink_BalconyS_C");

}

#pragma pack(pop)
