#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Notification_Elemental_Lightning

#include "Basic.hpp"

#include "Notification_Elemental_Lightning_classes.hpp"


#pragma pack(push, 0x4)
namespace SDK
{

// Function Notification_Elemental_Lightning.Notification_Elemental_Lightning_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ANotification_Elemental_Lightning_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Notification_Elemental_Lightning_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

#pragma pack(pop)
