#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PBWA_M2_QuarterWallHalf

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


#pragma pack(push, 0x4)
namespace SDK
{

// BlueprintGeneratedClass PBWA_M2_QuarterWallHalf.PBWA_M2_QuarterWallHalf_C
// 0x0000 (0x09F0 - 0x09F0)
class APBWA_M2_QuarterWallHalf_C final : public ABuildingWall
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PBWA_M2_QuarterWallHalf_C">();
	}
	static class APBWA_M2_QuarterWallHalf_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<APBWA_M2_QuarterWallHalf_C>();
	}
};
static_assert(alignof(APBWA_M2_QuarterWallHalf_C) == 0x000004, "Wrong alignment on APBWA_M2_QuarterWallHalf_C");
static_assert(sizeof(APBWA_M2_QuarterWallHalf_C) == 0x0009F0, "Wrong size on APBWA_M2_QuarterWallHalf_C");

}

#pragma pack(pop)
