#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PBWA_W3_HalfWallS

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


#pragma pack(push, 0x4)
namespace SDK
{

// BlueprintGeneratedClass PBWA_W3_HalfWallS.PBWA_W3_HalfWallS_C
// 0x0000 (0x09F0 - 0x09F0)
class APBWA_W3_HalfWallS_C final : public ABuildingWall
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PBWA_W3_HalfWallS_C">();
	}
	static class APBWA_W3_HalfWallS_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<APBWA_W3_HalfWallS_C>();
	}
};
static_assert(alignof(APBWA_W3_HalfWallS_C) == 0x000004, "Wrong alignment on APBWA_W3_HalfWallS_C");
static_assert(sizeof(APBWA_W3_HalfWallS_C) == 0x0009F0, "Wrong size on APBWA_W3_HalfWallS_C");

}

#pragma pack(pop)
