#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Prop_WaterTower_01

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


#pragma pack(push, 0x4)
namespace SDK
{

// BlueprintGeneratedClass Prop_WaterTower_01.Prop_WaterTower_01_C
// 0x0000 (0x0944 - 0x0944)
class AProp_WaterTower_01_C final : public ABuildingProp
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Prop_WaterTower_01_C">();
	}
	static class AProp_WaterTower_01_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AProp_WaterTower_01_C>();
	}
};
static_assert(alignof(AProp_WaterTower_01_C) == 0x000004, "Wrong alignment on AProp_WaterTower_01_C");
static_assert(sizeof(AProp_WaterTower_01_C) == 0x000944, "Wrong size on AProp_WaterTower_01_C");

}

#pragma pack(pop)
