#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Prop_TirePile_03

#include "Basic.hpp"

#include "Prop_TirePile_03_classes.hpp"
#include "Prop_TirePile_03_parameters.hpp"


#pragma pack(push, 0x4)
namespace SDK
{

// Function Prop_TirePile_03.Prop_TirePile_03_C.ExecuteUbergraph_Prop_TirePile_03
// ()
// Parameters:
// int32                                   EntryPoint                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AProp_TirePile_03_C::ExecuteUbergraph_Prop_TirePile_03(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Prop_TirePile_03_C", "ExecuteUbergraph_Prop_TirePile_03");

	Params::Prop_TirePile_03_C_ExecuteUbergraph_Prop_TirePile_03 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Prop_TirePile_03.Prop_TirePile_03_C.ReceiveBeginPlay
// (Event, Public, BlueprintEvent)

void AProp_TirePile_03_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Prop_TirePile_03_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Prop_TirePile_03.Prop_TirePile_03_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void AProp_TirePile_03_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Prop_TirePile_03_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

#pragma pack(pop)
