#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: School_Clock

#include "Basic.hpp"

#include "School_Clock_classes.hpp"
#include "School_Clock_parameters.hpp"


#pragma pack(push, 0x4)
namespace SDK
{

// Function School_Clock.School_CLock_C.ExecuteUbergraph_School_Clock
// (HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ASchool_CLock_C::ExecuteUbergraph_School_Clock(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("School_CLock_C", "ExecuteUbergraph_School_Clock");

	Params::School_CLock_C_ExecuteUbergraph_School_Clock Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function School_Clock.School_CLock_C.ReceiveBeginPlay
// (Event, Public, BlueprintEvent)

void ASchool_CLock_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("School_CLock_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function School_Clock.School_CLock_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ASchool_CLock_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("School_CLock_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function School_Clock.School_CLock_C.UpdateTime
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ASchool_CLock_C::UpdateTime()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("School_CLock_C", "UpdateTime");

	UObject::ProcessEvent(Func, nullptr);
}

}

#pragma pack(pop)
