#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SmasherPawn_Ice

#include "Basic.hpp"

#include "SmasherPawn_classes.hpp"


#pragma pack(push, 0x4)
namespace SDK
{

// BlueprintGeneratedClass SmasherPawn_Ice.SmasherPawn_Ice_C
// 0x0000 (0x1070 - 0x1070)
class ASmasherPawn_Ice_C final : public ASmasherPawn_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"SmasherPawn_Ice_C">();
	}
	static class ASmasherPawn_Ice_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ASmasherPawn_Ice_C>();
	}
};
static_assert(alignof(ASmasherPawn_Ice_C) == 0x000010, "Wrong alignment on ASmasherPawn_Ice_C");
static_assert(sizeof(ASmasherPawn_Ice_C) == 0x001070, "Wrong size on ASmasherPawn_Ice_C");

}

#pragma pack(pop)
