#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SmasherPawn_BossRampage

#include "Basic.hpp"

#include "GameplayTags_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"
#include "GameplayAbilities_structs.hpp"
#include "FortniteGame_structs.hpp"


#pragma pack(push, 0x4)
namespace SDK::Params
{

// Function SmasherPawn_BossRampage.SmasherPawn_BossRampage_C.ExecuteUbergraph_SmasherPawn_BossRampage
// 0x03D8 (0x03D8 - 0x0000)
struct SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FGuid                                  CallFunc_GetMissionGuid_ReturnValue;               // 0x0004(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_IsClosed_Variable;                       // 0x0014(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_15[0x3];                                       // 0x0015(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Variable;                                 // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_HasAuthority_ReturnValue;                 // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_21[0x3];                                       // 0x0021(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_GetSocketLocation_ReturnValue;            // 0x0024(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	class UParticleSystemComponent*               CallFunc_SpawnEmitterAtLocation_ReturnValue;       // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_HasAuthority_ReturnValue2;                // 0x0034(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_35[0x3];                                       // 0x0035(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FActiveGameplayEffectHandle            CallFunc_BP_ApplyGameplayEffectToSelf_ReturnValue; // 0x0038(0x0004)()
	bool                                          Temp_bool_IsClosed_Variable2;                      // 0x003C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3D[0x3];                                       // 0x003D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Subtract_IntInt_ReturnValue;              // 0x0040(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_LessEqual_IntInt_ReturnValue;             // 0x0044(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Has_Been_Initd_Variable;                 // 0x0045(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_HasAuthority_ReturnValue3;                // 0x0046(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_47[0x1];                                       // 0x0047(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Variable2;                                // 0x0048(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FActiveGameplayEffectHandle            CallFunc_BP_ApplyGameplayEffectToSelf_ReturnValue2; // 0x004C(0x0004)()
	int32                                         CallFunc_Add_IntInt_ReturnValue2;                  // 0x0050(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	float                                         K2Node_Event_Damage2;                              // 0x0054(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FGameplayTagContainer                  K2Node_Event_DamageTags2;                          // 0x0058(0x0018)(ConstParm)
	struct FVector                                K2Node_Event_Momentum2;                            // 0x0070(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FHitResult                             K2Node_Event_HitInfo2;                             // 0x007C(0x0080)(ConstParm, ContainsInstancedReference)
	class AController*                            K2Node_Event_InstigatedBy2;                        // 0x00FC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	class AActor*                                 K2Node_Event_DamageCauser2;                        // 0x0100(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FGameplayEffectContextHandle           K2Node_Event_EffectContext2;                       // 0x0104(0x000C)()
	float                                         CallFunc_GetHealth_ReturnValue;                    // 0x0110(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	float                                         CallFunc_GetMaxHealth_ReturnValue;                 // 0x0114(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	float                                         CallFunc_Divide_FloatFloat_ReturnValue;            // 0x0118(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	float                                         CallFunc_GetHealth_ReturnValue2;                   // 0x011C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	class UMaterialInstanceDynamic*               CallFunc_GetMIDForSkeletalMeshComponent_ReturnValue; // 0x0120(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x0124(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_Add_VectorVector_ReturnValue;             // 0x0130(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FLinearColor                           CallFunc_Conv_VectorToLinearColor_ReturnValue;     // 0x013C(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x014C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_TryActivateAbilitiesByTag_ReturnValue;    // 0x014D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_14E[0x2];                                      // 0x014E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         K2Node_CustomEvent_CurrentWave;                    // 0x0150(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	int32                                         K2Node_CustomEvent_BossStrength;                   // 0x0154(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	int32                                         K2Node_CustomEvent_Boss_speed;                     // 0x0158(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	float                                         CallFunc_GetTimelineLength_ReturnValue;            // 0x015C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	int32                                         CallFunc_Subtract_IntInt_ReturnValue2;             // 0x0160(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_LessEqual_IntInt_ReturnValue2;            // 0x0164(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x0165(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_166[0x2];                                      // 0x0166(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         Temp_float_Variable;                               // 0x0168(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	float                                         Temp_float_Variable2;                              // 0x016C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	class AActor*                                 K2Node_CustomEvent_RoarTarget;                     // 0x0170(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	class AAIController*                          CallFunc_GetAIController_ReturnValue;              // 0x0174(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	class AFortAIController*                      K2Node_DynamicCast_AsFort_AIController;            // 0x0178(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x017C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_17D[0x3];                                      // 0x017D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0180(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	class UBlackboardComponent*                   CallFunc_GetBlackboard_ReturnValue;                // 0x0184(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_NotEqual_IntInt_ReturnValue;              // 0x0188(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_189[0x3];                                      // 0x0189(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   CallFunc_MakeLiteralName_ReturnValue;              // 0x018C(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor)
	class AActor*                                 K2Node_ComponentBoundEvent_OtherActor2;            // 0x0194(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	class UPrimitiveComponent*                    K2Node_ComponentBoundEvent_OtherComp2;             // 0x0198(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	int32                                         K2Node_ComponentBoundEvent_OtherBodyIndex2;        // 0x019C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_ComponentBoundEvent_bFromSweep;             // 0x01A0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1A1[0x3];                                      // 0x01A1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             K2Node_ComponentBoundEvent_SweepResult;            // 0x01A4(0x0080)(ConstParm, ContainsInstancedReference)
	int32                                         CallFunc_Array_AddUnique_ReturnValue;              // 0x0224(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	EFortTeamAffiliation                          CallFunc_GetTeamAffiliation_ReturnValue;           // 0x0228(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_229[0x3];                                      // 0x0229(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 K2Node_ComponentBoundEvent_OtherActor;             // 0x022C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	class UPrimitiveComponent*                    K2Node_ComponentBoundEvent_OtherComp;              // 0x0230(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	int32                                         K2Node_ComponentBoundEvent_OtherBodyIndex;         // 0x0234(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x0238(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Array_RemoveItem_ReturnValue;             // 0x0239(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_23A[0x2];                                      // 0x023A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         Temp_float_Variable3;                              // 0x023C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Has_Been_Initd_Variable2;                // 0x0240(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_241[0x3];                                      // 0x0241(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue3;                  // 0x0244(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	int32                                         Temp_int_Variable3;                                // 0x0248(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue2;         // 0x024C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	float                                         K2Node_Select_Default;                             // 0x0258(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_LessEqual_FloatFloat_ReturnValue;         // 0x025C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_25D[0x3];                                      // 0x025D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UParticleSystemComponent*               CallFunc_SpawnEmitterAtLocation_ReturnValue2;      // 0x0260(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue3;         // 0x0264(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                K2Node_CustomEvent_Power_location;                 // 0x0270(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	class AAIController*                          CallFunc_GetAIController_ReturnValue2;             // 0x027C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	class AFortAIController*                      K2Node_DynamicCast_AsFort_AIController2;           // 0x0280(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_DynamicCast_bSuccess2;                      // 0x0284(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_285[0x3];                                      // 0x0285(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue4;         // 0x0288(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	class AActor*                                 CallFunc_GetGoalActor_ReturnValue;                 // 0x0294(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	class UParticleSystemComponent*               CallFunc_SpawnEmitterAtLocation_ReturnValue3;      // 0x0298(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue5;         // 0x029C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_Subtract_VectorVector_ReturnValue;        // 0x02A8(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_Add_VectorVector_ReturnValue2;            // 0x02B4(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	float                                         K2Node_Event_Damage;                               // 0x02C0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FGameplayTagContainer                  K2Node_Event_DamageTags;                           // 0x02C4(0x0018)(ConstParm)
	struct FVector                                K2Node_Event_Momentum;                             // 0x02DC(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FHitResult                             K2Node_Event_HitInfo;                              // 0x02E8(0x0080)(ConstParm, ContainsInstancedReference)
	class AFortPawn*                              K2Node_Event_InstigatedBy;                         // 0x0368(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	class AActor*                                 K2Node_Event_DamageCauser;                         // 0x036C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FGameplayEffectContextHandle           K2Node_Event_EffectContext;                        // 0x0370(0x000C)()
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue6;         // 0x037C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_GreaterEqual_IntInt_ReturnValue;          // 0x0388(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_389[0x3];                                      // 0x0389(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UParticleSystemComponent*               CallFunc_SpawnEmitterAtLocation_ReturnValue4;      // 0x038C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	TArray<struct FGameplayTag>                   K2Node_MakeArray_Array;                            // 0x0390(0x000C)(ZeroConstructor, ReferenceParm)
	struct FGameplayTagContainer                  K2Node_MakeStruct_GameplayTagContainer;            // 0x039C(0x0018)()
	bool                                          CallFunc_TryActivateAbilitiesByTag_ReturnValue2;   // 0x03B4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3B5[0x3];                                      // 0x03B5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGuid                                  CallFunc_GetMissionGuid_ReturnValue2;              // 0x03B8(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FGuid                                  CallFunc_GetMissionGuid_ReturnValue3;              // 0x03C8(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage) == 0x000004, "Wrong alignment on SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage");
static_assert(sizeof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage) == 0x0003D8, "Wrong size on SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, EntryPoint) == 0x000000, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::EntryPoint' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, CallFunc_GetMissionGuid_ReturnValue) == 0x000004, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::CallFunc_GetMissionGuid_ReturnValue' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, Temp_bool_IsClosed_Variable) == 0x000014, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::Temp_bool_IsClosed_Variable' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, Temp_int_Variable) == 0x000018, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::Temp_int_Variable' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, CallFunc_Add_IntInt_ReturnValue) == 0x00001C, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, CallFunc_HasAuthority_ReturnValue) == 0x000020, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::CallFunc_HasAuthority_ReturnValue' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, CallFunc_GetSocketLocation_ReturnValue) == 0x000024, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::CallFunc_GetSocketLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, CallFunc_SpawnEmitterAtLocation_ReturnValue) == 0x000030, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::CallFunc_SpawnEmitterAtLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, CallFunc_HasAuthority_ReturnValue2) == 0x000034, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::CallFunc_HasAuthority_ReturnValue2' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, CallFunc_BP_ApplyGameplayEffectToSelf_ReturnValue) == 0x000038, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::CallFunc_BP_ApplyGameplayEffectToSelf_ReturnValue' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, Temp_bool_IsClosed_Variable2) == 0x00003C, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::Temp_bool_IsClosed_Variable2' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, CallFunc_Subtract_IntInt_ReturnValue) == 0x000040, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::CallFunc_Subtract_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, CallFunc_LessEqual_IntInt_ReturnValue) == 0x000044, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::CallFunc_LessEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, Temp_bool_Has_Been_Initd_Variable) == 0x000045, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::Temp_bool_Has_Been_Initd_Variable' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, CallFunc_HasAuthority_ReturnValue3) == 0x000046, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::CallFunc_HasAuthority_ReturnValue3' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, Temp_int_Variable2) == 0x000048, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::Temp_int_Variable2' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, CallFunc_BP_ApplyGameplayEffectToSelf_ReturnValue2) == 0x00004C, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::CallFunc_BP_ApplyGameplayEffectToSelf_ReturnValue2' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, CallFunc_Add_IntInt_ReturnValue2) == 0x000050, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::CallFunc_Add_IntInt_ReturnValue2' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, K2Node_Event_Damage2) == 0x000054, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::K2Node_Event_Damage2' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, K2Node_Event_DamageTags2) == 0x000058, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::K2Node_Event_DamageTags2' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, K2Node_Event_Momentum2) == 0x000070, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::K2Node_Event_Momentum2' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, K2Node_Event_HitInfo2) == 0x00007C, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::K2Node_Event_HitInfo2' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, K2Node_Event_InstigatedBy2) == 0x0000FC, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::K2Node_Event_InstigatedBy2' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, K2Node_Event_DamageCauser2) == 0x000100, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::K2Node_Event_DamageCauser2' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, K2Node_Event_EffectContext2) == 0x000104, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::K2Node_Event_EffectContext2' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, CallFunc_GetHealth_ReturnValue) == 0x000110, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::CallFunc_GetHealth_ReturnValue' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, CallFunc_GetMaxHealth_ReturnValue) == 0x000114, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::CallFunc_GetMaxHealth_ReturnValue' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, CallFunc_Divide_FloatFloat_ReturnValue) == 0x000118, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::CallFunc_Divide_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, CallFunc_GetHealth_ReturnValue2) == 0x00011C, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::CallFunc_GetHealth_ReturnValue2' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, CallFunc_GetMIDForSkeletalMeshComponent_ReturnValue) == 0x000120, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::CallFunc_GetMIDForSkeletalMeshComponent_ReturnValue' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, CallFunc_K2_GetActorLocation_ReturnValue) == 0x000124, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, CallFunc_Add_VectorVector_ReturnValue) == 0x000130, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::CallFunc_Add_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, CallFunc_Conv_VectorToLinearColor_ReturnValue) == 0x00013C, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::CallFunc_Conv_VectorToLinearColor_ReturnValue' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, CallFunc_Less_IntInt_ReturnValue) == 0x00014C, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, CallFunc_TryActivateAbilitiesByTag_ReturnValue) == 0x00014D, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::CallFunc_TryActivateAbilitiesByTag_ReturnValue' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, K2Node_CustomEvent_CurrentWave) == 0x000150, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::K2Node_CustomEvent_CurrentWave' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, K2Node_CustomEvent_BossStrength) == 0x000154, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::K2Node_CustomEvent_BossStrength' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, K2Node_CustomEvent_Boss_speed) == 0x000158, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::K2Node_CustomEvent_Boss_speed' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, CallFunc_GetTimelineLength_ReturnValue) == 0x00015C, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::CallFunc_GetTimelineLength_ReturnValue' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, CallFunc_Subtract_IntInt_ReturnValue2) == 0x000160, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::CallFunc_Subtract_IntInt_ReturnValue2' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, CallFunc_LessEqual_IntInt_ReturnValue2) == 0x000164, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::CallFunc_LessEqual_IntInt_ReturnValue2' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, CallFunc_Greater_IntInt_ReturnValue) == 0x000165, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::CallFunc_Greater_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, Temp_float_Variable) == 0x000168, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::Temp_float_Variable' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, Temp_float_Variable2) == 0x00016C, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::Temp_float_Variable2' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, K2Node_CustomEvent_RoarTarget) == 0x000170, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::K2Node_CustomEvent_RoarTarget' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, CallFunc_GetAIController_ReturnValue) == 0x000174, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::CallFunc_GetAIController_ReturnValue' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, K2Node_DynamicCast_AsFort_AIController) == 0x000178, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::K2Node_DynamicCast_AsFort_AIController' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, K2Node_DynamicCast_bSuccess) == 0x00017C, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, CallFunc_Array_Length_ReturnValue) == 0x000180, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, CallFunc_GetBlackboard_ReturnValue) == 0x000184, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::CallFunc_GetBlackboard_ReturnValue' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, CallFunc_NotEqual_IntInt_ReturnValue) == 0x000188, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::CallFunc_NotEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, CallFunc_MakeLiteralName_ReturnValue) == 0x00018C, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::CallFunc_MakeLiteralName_ReturnValue' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, K2Node_ComponentBoundEvent_OtherActor2) == 0x000194, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::K2Node_ComponentBoundEvent_OtherActor2' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, K2Node_ComponentBoundEvent_OtherComp2) == 0x000198, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::K2Node_ComponentBoundEvent_OtherComp2' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, K2Node_ComponentBoundEvent_OtherBodyIndex2) == 0x00019C, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::K2Node_ComponentBoundEvent_OtherBodyIndex2' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, K2Node_ComponentBoundEvent_bFromSweep) == 0x0001A0, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::K2Node_ComponentBoundEvent_bFromSweep' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, K2Node_ComponentBoundEvent_SweepResult) == 0x0001A4, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::K2Node_ComponentBoundEvent_SweepResult' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, CallFunc_Array_AddUnique_ReturnValue) == 0x000224, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::CallFunc_Array_AddUnique_ReturnValue' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, CallFunc_GetTeamAffiliation_ReturnValue) == 0x000228, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::CallFunc_GetTeamAffiliation_ReturnValue' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, K2Node_ComponentBoundEvent_OtherActor) == 0x00022C, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::K2Node_ComponentBoundEvent_OtherActor' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, K2Node_ComponentBoundEvent_OtherComp) == 0x000230, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::K2Node_ComponentBoundEvent_OtherComp' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, K2Node_ComponentBoundEvent_OtherBodyIndex) == 0x000234, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::K2Node_ComponentBoundEvent_OtherBodyIndex' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, K2Node_SwitchEnum_CmpSuccess) == 0x000238, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::K2Node_SwitchEnum_CmpSuccess' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, CallFunc_Array_RemoveItem_ReturnValue) == 0x000239, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::CallFunc_Array_RemoveItem_ReturnValue' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, Temp_float_Variable3) == 0x00023C, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::Temp_float_Variable3' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, Temp_bool_Has_Been_Initd_Variable2) == 0x000240, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::Temp_bool_Has_Been_Initd_Variable2' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, CallFunc_Add_IntInt_ReturnValue3) == 0x000244, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::CallFunc_Add_IntInt_ReturnValue3' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, Temp_int_Variable3) == 0x000248, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::Temp_int_Variable3' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, CallFunc_K2_GetActorLocation_ReturnValue2) == 0x00024C, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::CallFunc_K2_GetActorLocation_ReturnValue2' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, K2Node_Select_Default) == 0x000258, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, CallFunc_LessEqual_FloatFloat_ReturnValue) == 0x00025C, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::CallFunc_LessEqual_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, CallFunc_SpawnEmitterAtLocation_ReturnValue2) == 0x000260, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::CallFunc_SpawnEmitterAtLocation_ReturnValue2' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, CallFunc_K2_GetActorLocation_ReturnValue3) == 0x000264, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::CallFunc_K2_GetActorLocation_ReturnValue3' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, K2Node_CustomEvent_Power_location) == 0x000270, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::K2Node_CustomEvent_Power_location' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, CallFunc_GetAIController_ReturnValue2) == 0x00027C, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::CallFunc_GetAIController_ReturnValue2' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, K2Node_DynamicCast_AsFort_AIController2) == 0x000280, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::K2Node_DynamicCast_AsFort_AIController2' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, K2Node_DynamicCast_bSuccess2) == 0x000284, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::K2Node_DynamicCast_bSuccess2' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, CallFunc_K2_GetActorLocation_ReturnValue4) == 0x000288, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::CallFunc_K2_GetActorLocation_ReturnValue4' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, CallFunc_GetGoalActor_ReturnValue) == 0x000294, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::CallFunc_GetGoalActor_ReturnValue' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, CallFunc_SpawnEmitterAtLocation_ReturnValue3) == 0x000298, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::CallFunc_SpawnEmitterAtLocation_ReturnValue3' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, CallFunc_K2_GetActorLocation_ReturnValue5) == 0x00029C, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::CallFunc_K2_GetActorLocation_ReturnValue5' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, CallFunc_Subtract_VectorVector_ReturnValue) == 0x0002A8, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::CallFunc_Subtract_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, CallFunc_Add_VectorVector_ReturnValue2) == 0x0002B4, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::CallFunc_Add_VectorVector_ReturnValue2' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, K2Node_Event_Damage) == 0x0002C0, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::K2Node_Event_Damage' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, K2Node_Event_DamageTags) == 0x0002C4, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::K2Node_Event_DamageTags' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, K2Node_Event_Momentum) == 0x0002DC, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::K2Node_Event_Momentum' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, K2Node_Event_HitInfo) == 0x0002E8, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::K2Node_Event_HitInfo' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, K2Node_Event_InstigatedBy) == 0x000368, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::K2Node_Event_InstigatedBy' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, K2Node_Event_DamageCauser) == 0x00036C, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::K2Node_Event_DamageCauser' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, K2Node_Event_EffectContext) == 0x000370, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::K2Node_Event_EffectContext' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, CallFunc_K2_GetActorLocation_ReturnValue6) == 0x00037C, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::CallFunc_K2_GetActorLocation_ReturnValue6' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, CallFunc_GreaterEqual_IntInt_ReturnValue) == 0x000388, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::CallFunc_GreaterEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, CallFunc_SpawnEmitterAtLocation_ReturnValue4) == 0x00038C, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::CallFunc_SpawnEmitterAtLocation_ReturnValue4' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, K2Node_MakeArray_Array) == 0x000390, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, K2Node_MakeStruct_GameplayTagContainer) == 0x00039C, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::K2Node_MakeStruct_GameplayTagContainer' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, CallFunc_TryActivateAbilitiesByTag_ReturnValue2) == 0x0003B4, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::CallFunc_TryActivateAbilitiesByTag_ReturnValue2' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, CallFunc_GetMissionGuid_ReturnValue2) == 0x0003B8, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::CallFunc_GetMissionGuid_ReturnValue2' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage, CallFunc_GetMissionGuid_ReturnValue3) == 0x0003C8, "Member 'SmasherPawn_BossRampage_C_ExecuteUbergraph_SmasherPawn_BossRampage::CallFunc_GetMissionGuid_ReturnValue3' has a wrong offset!");

// Function SmasherPawn_BossRampage.SmasherPawn_BossRampage_C.OnDeathPlayEffects
// 0x00BC (0x00BC - 0x0000)
struct SmasherPawn_BossRampage_C_OnDeathPlayEffects final
{
public:
	float                                         Damage;                                            // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FGameplayTagContainer                  DamageTags;                                        // 0x0004(0x0018)(ConstParm, Parm, OutParm, ReferenceParm)
	struct FVector                                Momentum;                                          // 0x001C(0x000C)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FHitResult                             HitInfo;                                           // 0x0028(0x0080)(ConstParm, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
	class AFortPawn*                              InstigatedBy;                                      // 0x00A8(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	class AActor*                                 DamageCauser;                                      // 0x00AC(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FGameplayEffectContextHandle           EffectContext;                                     // 0x00B0(0x000C)(Parm)
};
static_assert(alignof(SmasherPawn_BossRampage_C_OnDeathPlayEffects) == 0x000004, "Wrong alignment on SmasherPawn_BossRampage_C_OnDeathPlayEffects");
static_assert(sizeof(SmasherPawn_BossRampage_C_OnDeathPlayEffects) == 0x0000BC, "Wrong size on SmasherPawn_BossRampage_C_OnDeathPlayEffects");
static_assert(offsetof(SmasherPawn_BossRampage_C_OnDeathPlayEffects, Damage) == 0x000000, "Member 'SmasherPawn_BossRampage_C_OnDeathPlayEffects::Damage' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_OnDeathPlayEffects, DamageTags) == 0x000004, "Member 'SmasherPawn_BossRampage_C_OnDeathPlayEffects::DamageTags' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_OnDeathPlayEffects, Momentum) == 0x00001C, "Member 'SmasherPawn_BossRampage_C_OnDeathPlayEffects::Momentum' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_OnDeathPlayEffects, HitInfo) == 0x000028, "Member 'SmasherPawn_BossRampage_C_OnDeathPlayEffects::HitInfo' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_OnDeathPlayEffects, InstigatedBy) == 0x0000A8, "Member 'SmasherPawn_BossRampage_C_OnDeathPlayEffects::InstigatedBy' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_OnDeathPlayEffects, DamageCauser) == 0x0000AC, "Member 'SmasherPawn_BossRampage_C_OnDeathPlayEffects::DamageCauser' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_OnDeathPlayEffects, EffectContext) == 0x0000B0, "Member 'SmasherPawn_BossRampage_C_OnDeathPlayEffects::EffectContext' has a wrong offset!");

// Function SmasherPawn_BossRampage.SmasherPawn_BossRampage_C.PowerUpFX
// 0x000C (0x000C - 0x0000)
struct SmasherPawn_BossRampage_C_PowerUpFX final
{
public:
	struct FVector                                Power_location;                                    // 0x0000(0x000C)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(SmasherPawn_BossRampage_C_PowerUpFX) == 0x000004, "Wrong alignment on SmasherPawn_BossRampage_C_PowerUpFX");
static_assert(sizeof(SmasherPawn_BossRampage_C_PowerUpFX) == 0x00000C, "Wrong size on SmasherPawn_BossRampage_C_PowerUpFX");
static_assert(offsetof(SmasherPawn_BossRampage_C_PowerUpFX, Power_location) == 0x000000, "Member 'SmasherPawn_BossRampage_C_PowerUpFX::Power_location' has a wrong offset!");

// Function SmasherPawn_BossRampage.SmasherPawn_BossRampage_C.BndEvt__RadialMeleeRadius_K2Node_ComponentBoundEvent_212_ComponentEndOverlapSignature__DelegateSignature
// 0x000C (0x000C - 0x0000)
struct SmasherPawn_BossRampage_C_BndEvt__RadialMeleeRadius_K2Node_ComponentBoundEvent_212_ComponentEndOverlapSignature__DelegateSignature final
{
public:
	class AActor*                                 OtherActor;                                        // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	class UPrimitiveComponent*                    OtherComp;                                         // 0x0004(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	int32                                         OtherBodyIndex;                                    // 0x0008(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(SmasherPawn_BossRampage_C_BndEvt__RadialMeleeRadius_K2Node_ComponentBoundEvent_212_ComponentEndOverlapSignature__DelegateSignature) == 0x000004, "Wrong alignment on SmasherPawn_BossRampage_C_BndEvt__RadialMeleeRadius_K2Node_ComponentBoundEvent_212_ComponentEndOverlapSignature__DelegateSignature");
static_assert(sizeof(SmasherPawn_BossRampage_C_BndEvt__RadialMeleeRadius_K2Node_ComponentBoundEvent_212_ComponentEndOverlapSignature__DelegateSignature) == 0x00000C, "Wrong size on SmasherPawn_BossRampage_C_BndEvt__RadialMeleeRadius_K2Node_ComponentBoundEvent_212_ComponentEndOverlapSignature__DelegateSignature");
static_assert(offsetof(SmasherPawn_BossRampage_C_BndEvt__RadialMeleeRadius_K2Node_ComponentBoundEvent_212_ComponentEndOverlapSignature__DelegateSignature, OtherActor) == 0x000000, "Member 'SmasherPawn_BossRampage_C_BndEvt__RadialMeleeRadius_K2Node_ComponentBoundEvent_212_ComponentEndOverlapSignature__DelegateSignature::OtherActor' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_BndEvt__RadialMeleeRadius_K2Node_ComponentBoundEvent_212_ComponentEndOverlapSignature__DelegateSignature, OtherComp) == 0x000004, "Member 'SmasherPawn_BossRampage_C_BndEvt__RadialMeleeRadius_K2Node_ComponentBoundEvent_212_ComponentEndOverlapSignature__DelegateSignature::OtherComp' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_BndEvt__RadialMeleeRadius_K2Node_ComponentBoundEvent_212_ComponentEndOverlapSignature__DelegateSignature, OtherBodyIndex) == 0x000008, "Member 'SmasherPawn_BossRampage_C_BndEvt__RadialMeleeRadius_K2Node_ComponentBoundEvent_212_ComponentEndOverlapSignature__DelegateSignature::OtherBodyIndex' has a wrong offset!");

// Function SmasherPawn_BossRampage.SmasherPawn_BossRampage_C.BndEvt__RadialMeleeRadius_K2Node_ComponentBoundEvent_210_ComponentBeginOverlapSignature__DelegateSignature
// 0x0090 (0x0090 - 0x0000)
struct SmasherPawn_BossRampage_C_BndEvt__RadialMeleeRadius_K2Node_ComponentBoundEvent_210_ComponentBeginOverlapSignature__DelegateSignature final
{
public:
	class AActor*                                 OtherActor;                                        // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	class UPrimitiveComponent*                    OtherComp;                                         // 0x0004(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	int32                                         OtherBodyIndex;                                    // 0x0008(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          bFromSweep;                                        // 0x000C(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_D[0x3];                                        // 0x000D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             SweepResult;                                       // 0x0010(0x0080)(ConstParm, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
};
static_assert(alignof(SmasherPawn_BossRampage_C_BndEvt__RadialMeleeRadius_K2Node_ComponentBoundEvent_210_ComponentBeginOverlapSignature__DelegateSignature) == 0x000004, "Wrong alignment on SmasherPawn_BossRampage_C_BndEvt__RadialMeleeRadius_K2Node_ComponentBoundEvent_210_ComponentBeginOverlapSignature__DelegateSignature");
static_assert(sizeof(SmasherPawn_BossRampage_C_BndEvt__RadialMeleeRadius_K2Node_ComponentBoundEvent_210_ComponentBeginOverlapSignature__DelegateSignature) == 0x000090, "Wrong size on SmasherPawn_BossRampage_C_BndEvt__RadialMeleeRadius_K2Node_ComponentBoundEvent_210_ComponentBeginOverlapSignature__DelegateSignature");
static_assert(offsetof(SmasherPawn_BossRampage_C_BndEvt__RadialMeleeRadius_K2Node_ComponentBoundEvent_210_ComponentBeginOverlapSignature__DelegateSignature, OtherActor) == 0x000000, "Member 'SmasherPawn_BossRampage_C_BndEvt__RadialMeleeRadius_K2Node_ComponentBoundEvent_210_ComponentBeginOverlapSignature__DelegateSignature::OtherActor' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_BndEvt__RadialMeleeRadius_K2Node_ComponentBoundEvent_210_ComponentBeginOverlapSignature__DelegateSignature, OtherComp) == 0x000004, "Member 'SmasherPawn_BossRampage_C_BndEvt__RadialMeleeRadius_K2Node_ComponentBoundEvent_210_ComponentBeginOverlapSignature__DelegateSignature::OtherComp' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_BndEvt__RadialMeleeRadius_K2Node_ComponentBoundEvent_210_ComponentBeginOverlapSignature__DelegateSignature, OtherBodyIndex) == 0x000008, "Member 'SmasherPawn_BossRampage_C_BndEvt__RadialMeleeRadius_K2Node_ComponentBoundEvent_210_ComponentBeginOverlapSignature__DelegateSignature::OtherBodyIndex' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_BndEvt__RadialMeleeRadius_K2Node_ComponentBoundEvent_210_ComponentBeginOverlapSignature__DelegateSignature, bFromSweep) == 0x00000C, "Member 'SmasherPawn_BossRampage_C_BndEvt__RadialMeleeRadius_K2Node_ComponentBoundEvent_210_ComponentBeginOverlapSignature__DelegateSignature::bFromSweep' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_BndEvt__RadialMeleeRadius_K2Node_ComponentBoundEvent_210_ComponentBeginOverlapSignature__DelegateSignature, SweepResult) == 0x000010, "Member 'SmasherPawn_BossRampage_C_BndEvt__RadialMeleeRadius_K2Node_ComponentBoundEvent_210_ComponentBeginOverlapSignature__DelegateSignature::SweepResult' has a wrong offset!");

// Function SmasherPawn_BossRampage.SmasherPawn_BossRampage_C.RampageRoarComplete
// 0x0004 (0x0004 - 0x0000)
struct SmasherPawn_BossRampage_C_RampageRoarComplete final
{
public:
	class AActor*                                 RoarTarget;                                        // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(SmasherPawn_BossRampage_C_RampageRoarComplete) == 0x000004, "Wrong alignment on SmasherPawn_BossRampage_C_RampageRoarComplete");
static_assert(sizeof(SmasherPawn_BossRampage_C_RampageRoarComplete) == 0x000004, "Wrong size on SmasherPawn_BossRampage_C_RampageRoarComplete");
static_assert(offsetof(SmasherPawn_BossRampage_C_RampageRoarComplete, RoarTarget) == 0x000000, "Member 'SmasherPawn_BossRampage_C_RampageRoarComplete::RoarTarget' has a wrong offset!");

// Function SmasherPawn_BossRampage.SmasherPawn_BossRampage_C.SetBossStats
// 0x000C (0x000C - 0x0000)
struct SmasherPawn_BossRampage_C_SetBossStats final
{
public:
	int32                                         CurrentWave_0;                                     // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	int32                                         BossStrength;                                      // 0x0004(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	int32                                         Boss_speed;                                        // 0x0008(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(SmasherPawn_BossRampage_C_SetBossStats) == 0x000004, "Wrong alignment on SmasherPawn_BossRampage_C_SetBossStats");
static_assert(sizeof(SmasherPawn_BossRampage_C_SetBossStats) == 0x00000C, "Wrong size on SmasherPawn_BossRampage_C_SetBossStats");
static_assert(offsetof(SmasherPawn_BossRampage_C_SetBossStats, CurrentWave_0) == 0x000000, "Member 'SmasherPawn_BossRampage_C_SetBossStats::CurrentWave_0' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_SetBossStats, BossStrength) == 0x000004, "Member 'SmasherPawn_BossRampage_C_SetBossStats::BossStrength' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_SetBossStats, Boss_speed) == 0x000008, "Member 'SmasherPawn_BossRampage_C_SetBossStats::Boss_speed' has a wrong offset!");

// Function SmasherPawn_BossRampage.SmasherPawn_BossRampage_C.OnDamageServer
// 0x00BC (0x00BC - 0x0000)
struct SmasherPawn_BossRampage_C_OnDamageServer final
{
public:
	float                                         Damage;                                            // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FGameplayTagContainer                  DamageTags;                                        // 0x0004(0x0018)(ConstParm, Parm, OutParm, ReferenceParm)
	struct FVector                                Momentum;                                          // 0x001C(0x000C)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FHitResult                             HitInfo;                                           // 0x0028(0x0080)(ConstParm, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
	class AController*                            InstigatedBy;                                      // 0x00A8(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	class AActor*                                 DamageCauser;                                      // 0x00AC(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FGameplayEffectContextHandle           EffectContext;                                     // 0x00B0(0x000C)(Parm)
};
static_assert(alignof(SmasherPawn_BossRampage_C_OnDamageServer) == 0x000004, "Wrong alignment on SmasherPawn_BossRampage_C_OnDamageServer");
static_assert(sizeof(SmasherPawn_BossRampage_C_OnDamageServer) == 0x0000BC, "Wrong size on SmasherPawn_BossRampage_C_OnDamageServer");
static_assert(offsetof(SmasherPawn_BossRampage_C_OnDamageServer, Damage) == 0x000000, "Member 'SmasherPawn_BossRampage_C_OnDamageServer::Damage' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_OnDamageServer, DamageTags) == 0x000004, "Member 'SmasherPawn_BossRampage_C_OnDamageServer::DamageTags' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_OnDamageServer, Momentum) == 0x00001C, "Member 'SmasherPawn_BossRampage_C_OnDamageServer::Momentum' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_OnDamageServer, HitInfo) == 0x000028, "Member 'SmasherPawn_BossRampage_C_OnDamageServer::HitInfo' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_OnDamageServer, InstigatedBy) == 0x0000A8, "Member 'SmasherPawn_BossRampage_C_OnDamageServer::InstigatedBy' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_OnDamageServer, DamageCauser) == 0x0000AC, "Member 'SmasherPawn_BossRampage_C_OnDamageServer::DamageCauser' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_OnDamageServer, EffectContext) == 0x0000B0, "Member 'SmasherPawn_BossRampage_C_OnDamageServer::EffectContext' has a wrong offset!");

// Function SmasherPawn_BossRampage.SmasherPawn_BossRampage_C.UserConstructionScript
// 0x0004 (0x0004 - 0x0000)
struct SmasherPawn_BossRampage_C_UserConstructionScript final
{
public:
	class UMaterialInstanceDynamic*               CallFunc_CreateDynamicMaterialInstance_ReturnValue; // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(SmasherPawn_BossRampage_C_UserConstructionScript) == 0x000004, "Wrong alignment on SmasherPawn_BossRampage_C_UserConstructionScript");
static_assert(sizeof(SmasherPawn_BossRampage_C_UserConstructionScript) == 0x000004, "Wrong size on SmasherPawn_BossRampage_C_UserConstructionScript");
static_assert(offsetof(SmasherPawn_BossRampage_C_UserConstructionScript, CallFunc_CreateDynamicMaterialInstance_ReturnValue) == 0x000000, "Member 'SmasherPawn_BossRampage_C_UserConstructionScript::CallFunc_CreateDynamicMaterialInstance_ReturnValue' has a wrong offset!");

// Function SmasherPawn_BossRampage.SmasherPawn_BossRampage_C.OnRep_StrengthLevel
// 0x0028 (0x0028 - 0x0000)
struct SmasherPawn_BossRampage_C_OnRep_StrengthLevel final
{
public:
	int32                                         Temp_int_Variable;                                 // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	float                                         Temp_float_Variable;                               // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	float                                         Temp_float_Variable2;                              // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	float                                         Temp_float_Variable3;                              // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	float                                         Temp_float_Variable4;                              // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	float                                         Temp_float_Variable5;                              // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	float                                         K2Node_Select_Default;                             // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	int32                                         CallFunc_Subtract_IntInt_ReturnValue;              // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_LessEqual_IntInt_ReturnValue;             // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_21[0x3];                                       // 0x0021(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_Conv_IntToFloat_ReturnValue;              // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(SmasherPawn_BossRampage_C_OnRep_StrengthLevel) == 0x000004, "Wrong alignment on SmasherPawn_BossRampage_C_OnRep_StrengthLevel");
static_assert(sizeof(SmasherPawn_BossRampage_C_OnRep_StrengthLevel) == 0x000028, "Wrong size on SmasherPawn_BossRampage_C_OnRep_StrengthLevel");
static_assert(offsetof(SmasherPawn_BossRampage_C_OnRep_StrengthLevel, Temp_int_Variable) == 0x000000, "Member 'SmasherPawn_BossRampage_C_OnRep_StrengthLevel::Temp_int_Variable' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_OnRep_StrengthLevel, Temp_float_Variable) == 0x000004, "Member 'SmasherPawn_BossRampage_C_OnRep_StrengthLevel::Temp_float_Variable' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_OnRep_StrengthLevel, Temp_float_Variable2) == 0x000008, "Member 'SmasherPawn_BossRampage_C_OnRep_StrengthLevel::Temp_float_Variable2' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_OnRep_StrengthLevel, Temp_float_Variable3) == 0x00000C, "Member 'SmasherPawn_BossRampage_C_OnRep_StrengthLevel::Temp_float_Variable3' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_OnRep_StrengthLevel, Temp_float_Variable4) == 0x000010, "Member 'SmasherPawn_BossRampage_C_OnRep_StrengthLevel::Temp_float_Variable4' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_OnRep_StrengthLevel, Temp_float_Variable5) == 0x000014, "Member 'SmasherPawn_BossRampage_C_OnRep_StrengthLevel::Temp_float_Variable5' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_OnRep_StrengthLevel, K2Node_Select_Default) == 0x000018, "Member 'SmasherPawn_BossRampage_C_OnRep_StrengthLevel::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_OnRep_StrengthLevel, CallFunc_Subtract_IntInt_ReturnValue) == 0x00001C, "Member 'SmasherPawn_BossRampage_C_OnRep_StrengthLevel::CallFunc_Subtract_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_OnRep_StrengthLevel, CallFunc_LessEqual_IntInt_ReturnValue) == 0x000020, "Member 'SmasherPawn_BossRampage_C_OnRep_StrengthLevel::CallFunc_LessEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(SmasherPawn_BossRampage_C_OnRep_StrengthLevel, CallFunc_Conv_IntToFloat_ReturnValue) == 0x000024, "Member 'SmasherPawn_BossRampage_C_OnRep_StrengthLevel::CallFunc_Conv_IntToFloat_ReturnValue' has a wrong offset!");

}

#pragma pack(pop)
