#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ThreatCloudSpawns

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


#pragma pack(push, 0x4)
namespace SDK
{

// UserDefinedStruct ThreatCloudSpawns.ThreatCloudSpawns
// 0x0010 (0x0010 - 0x0000)
struct FThreatCloudSpawns final
{
public:
	class AActor*                                 Relic_2;                                           // 0x0000(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                EndLocation_5;                                     // 0x0004(0x000C)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(FThreatCloudSpawns) == 0x000004, "Wrong alignment on FThreatCloudSpawns");
static_assert(sizeof(FThreatCloudSpawns) == 0x000010, "Wrong size on FThreatCloudSpawns");
static_assert(offsetof(FThreatCloudSpawns, Relic_2) == 0x000000, "Member 'FThreatCloudSpawns::Relic_2' has a wrong offset!");
static_assert(offsetof(FThreatCloudSpawns, EndLocation_5) == 0x000004, "Member 'FThreatCloudSpawns::EndLocation_5' has a wrong offset!");

}

#pragma pack(pop)
