#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Tracer_Shotgun

#include "Basic.hpp"

#include "Tracer_Shotgun_classes.hpp"
#include "Tracer_Shotgun_parameters.hpp"


#pragma pack(push, 0x4)
namespace SDK
{

// Function Tracer_Shotgun.Tracer_Shotgun_C.ExecuteUbergraph_Tracer_Shotgun
// ()
// Parameters:
// int32                                   EntryPoint                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ATracer_Shotgun_C::ExecuteUbergraph_Tracer_Shotgun(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Tracer_Shotgun_C", "ExecuteUbergraph_Tracer_Shotgun");

	Params::Tracer_Shotgun_C_ExecuteUbergraph_Tracer_Shotgun Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Tracer_Shotgun.Tracer_Shotgun_C.ReceiveBeginPlay
// (Event, Public, BlueprintEvent)

void ATracer_Shotgun_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Tracer_Shotgun_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Tracer_Shotgun.Tracer_Shotgun_C.UserConstructionScript
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ATracer_Shotgun_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Tracer_Shotgun_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

#pragma pack(pop)
