#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Trap_Wall_HeavyMetal

#include "Basic.hpp"

#include "Trap_Wall_HeavyMetal_classes.hpp"
#include "Trap_Wall_HeavyMetal_parameters.hpp"


#pragma pack(push, 0x4)
namespace SDK
{

// Function Trap_Wall_HeavyMetal.Trap_Wall_HeavyMetal_C.ExecuteUbergraph_Trap_Wall_HeavyMetal
// (HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ATrap_Wall_HeavyMetal_C::ExecuteUbergraph_Trap_Wall_HeavyMetal(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Trap_Wall_HeavyMetal_C", "ExecuteUbergraph_Trap_Wall_HeavyMetal");

	Params::Trap_Wall_HeavyMetal_C_ExecuteUbergraph_Trap_Wall_HeavyMetal Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Trap_Wall_HeavyMetal.Trap_Wall_HeavyMetal_C.OnOutOfDurability
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void ATrap_Wall_HeavyMetal_C::OnOutOfDurability()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Trap_Wall_HeavyMetal_C", "OnOutOfDurability");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Trap_Wall_HeavyMetal.Trap_Wall_HeavyMetal_C.GameplayCue.Abilities.Activation.Traps.ReloadBegin
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// EGameplayCueEvent                       EventType                                              (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// const struct FGameplayCueParameters&    Parameters                                             (Parm)

void ATrap_Wall_HeavyMetal_C::GameplayCue_Abilities_Activation_Traps_ReloadBegin(EGameplayCueEvent EventType, const struct FGameplayCueParameters& Parameters)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Trap_Wall_HeavyMetal_C", "GameplayCue.Abilities.Activation.Traps.ReloadBegin");

	Params::Trap_Wall_HeavyMetal_C_GameplayCue_Abilities_Activation_Traps_ReloadBegin Parms{};

	Parms.EventType = EventType;
	Parms.Parameters = std::move(Parameters);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Trap_Wall_HeavyMetal.Trap_Wall_HeavyMetal_C.GameplayCue.Abilities.Activation.Traps.ActivateTrap
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// EGameplayCueEvent                       EventType                                              (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// const struct FGameplayCueParameters&    Parameters                                             (Parm)

void ATrap_Wall_HeavyMetal_C::GameplayCue_Abilities_Activation_Traps_ActivateTrap(EGameplayCueEvent EventType, const struct FGameplayCueParameters& Parameters)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Trap_Wall_HeavyMetal_C", "GameplayCue.Abilities.Activation.Traps.ActivateTrap");

	Params::Trap_Wall_HeavyMetal_C_GameplayCue_Abilities_Activation_Traps_ActivateTrap Parms{};

	Parms.EventType = EventType;
	Parms.Parameters = std::move(Parameters);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Trap_Wall_HeavyMetal.Trap_Wall_HeavyMetal_C.OnReloadEnd
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void ATrap_Wall_HeavyMetal_C::OnReloadEnd()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Trap_Wall_HeavyMetal_C", "OnReloadEnd");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Trap_Wall_HeavyMetal.Trap_Wall_HeavyMetal_C.OnFinishedBuilding
// (Event, Public, BlueprintEvent)

void ATrap_Wall_HeavyMetal_C::OnFinishedBuilding()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Trap_Wall_HeavyMetal_C", "OnFinishedBuilding");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Trap_Wall_HeavyMetal.Trap_Wall_HeavyMetal_C.OnPlaced
// (Event, Public, BlueprintEvent)

void ATrap_Wall_HeavyMetal_C::OnPlaced()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Trap_Wall_HeavyMetal_C", "OnPlaced");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Trap_Wall_HeavyMetal.Trap_Wall_HeavyMetal_C.Timeline_4__UpdateFunc
// (BlueprintEvent)

void ATrap_Wall_HeavyMetal_C::Timeline_4__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Trap_Wall_HeavyMetal_C", "Timeline_4__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Trap_Wall_HeavyMetal.Trap_Wall_HeavyMetal_C.Timeline_4__FinishedFunc
// (BlueprintEvent)

void ATrap_Wall_HeavyMetal_C::Timeline_4__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Trap_Wall_HeavyMetal_C", "Timeline_4__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Trap_Wall_HeavyMetal.Trap_Wall_HeavyMetal_C.Timeline_2__UpdateFunc
// (BlueprintEvent)

void ATrap_Wall_HeavyMetal_C::Timeline_2__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Trap_Wall_HeavyMetal_C", "Timeline_2__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Trap_Wall_HeavyMetal.Trap_Wall_HeavyMetal_C.Timeline_2__FinishedFunc
// (BlueprintEvent)

void ATrap_Wall_HeavyMetal_C::Timeline_2__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Trap_Wall_HeavyMetal_C", "Timeline_2__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Trap_Wall_HeavyMetal.Trap_Wall_HeavyMetal_C.Timeline_1__UpdateFunc
// (BlueprintEvent)

void ATrap_Wall_HeavyMetal_C::Timeline_1__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Trap_Wall_HeavyMetal_C", "Timeline_1__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Trap_Wall_HeavyMetal.Trap_Wall_HeavyMetal_C.Timeline_1__FinishedFunc
// (BlueprintEvent)

void ATrap_Wall_HeavyMetal_C::Timeline_1__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Trap_Wall_HeavyMetal_C", "Timeline_1__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Trap_Wall_HeavyMetal.Trap_Wall_HeavyMetal_C.Timeline_0__UpdateFunc
// (BlueprintEvent)

void ATrap_Wall_HeavyMetal_C::Timeline_0__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Trap_Wall_HeavyMetal_C", "Timeline_0__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Trap_Wall_HeavyMetal.Trap_Wall_HeavyMetal_C.Timeline_0__FinishedFunc
// (BlueprintEvent)

void ATrap_Wall_HeavyMetal_C::Timeline_0__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Trap_Wall_HeavyMetal_C", "Timeline_0__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Trap_Wall_HeavyMetal.Trap_Wall_HeavyMetal_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ATrap_Wall_HeavyMetal_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Trap_Wall_HeavyMetal_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

#pragma pack(pop)
