#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WaterPipe02

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteGame_classes.hpp"


#pragma pack(push, 0x4)
namespace SDK
{

// BlueprintGeneratedClass WaterPipe02.WaterPipe02_C
// 0x0004 (0x0948 - 0x0944)
class AWaterPipe02_C final : public ABuildingProp
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0944(0x0004)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_WaterPipe02(int32 EntryPoint);
	void OnDamagePlayEffects(float Damage, const struct FGameplayTagContainer& DamageTags, const struct FVector& Momentum, const struct FHitResult& HitInfo, class AFortPawn* InstigatedBy, class AActor* DamageCauser, const struct FGameplayEffectContextHandle& EffectContext);
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WaterPipe02_C">();
	}
	static class AWaterPipe02_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AWaterPipe02_C>();
	}
};
static_assert(alignof(AWaterPipe02_C) == 0x000004, "Wrong alignment on AWaterPipe02_C");
static_assert(sizeof(AWaterPipe02_C) == 0x000948, "Wrong size on AWaterPipe02_C");
static_assert(offsetof(AWaterPipe02_C, UberGraphFrame) == 0x000944, "Member 'AWaterPipe02_C::UberGraphFrame' has a wrong offset!");

}

#pragma pack(pop)
